dhis2/data-visualizer-app

- package.json
- src/App.js
- src/__tests__/App.spec.js
- src/index.js
- yarn.lock
- D2UIApp is only needed to set the theme for MUI v0.x required by some
components like translation and sharing dialogs.
- Since D2UIApp is not setting d2 in the context anymore, do that in the
app instead.
> Fix use of D2UIApp and init d2 in the app

- packages/app/src/index.js
This plugin is deprecated and actually breaks with React 16.4. According to the author, it is no longer needed anyway.
https://github.com/zilverline/react-tap-event-plugin
> task/Remove injectTapEventPlugin that breaks with React 16.4

- packages/app/package.json
- yarn.lock
The previous version of period-selector-dialog use the import syntax that resulted in the entire material-ui/icons being included in the bundle. Which was huge.
> Use latest period-selector-dialog for improved treeshaking

- packages/app/package.json
- packages/app/src/assets/YearOverYearLineIcon.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeIcon.js
- packages/app/src/modules/chartTypes.js
- packages/app/src/reducers/__tests__/current.spec.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/current.js
- packages/app/src/reducers/ui.js
- yarn.lock
This is to use the same naming as the backend and allow for new chart
types like YEAR_OVER_YEAR_COLUMN.
> Rename YEAR_ON_YEAR to YEAR_OVER_YEAR_LINE chart type

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/assets/YearOverYearColumnIcon.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeIcon.js
- packages/app/src/modules/chartTypes.js
- packages/app/src/modules/ui.js
- packages/app/src/modules/yearOnYear.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/current.js
- yarn.lock
Requires updated d2-charts-api before merging to master.
A new icon is needed, for now it's the same as the year over year line one.
> Add support for Year over Year column chart type

- packages/app/src/components/Dimensions/DimensionList.js
fix/change fn name for filtering text in Dimensions
From searchTextContains
To: FilterTextContains
> fix/change fn name for filtering text in Dimensions

- packages/app/src/components/App.css
- packages/app/src/components/App.js
- packages/app/src/components/Dimensions/Dimensions.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
To make the CSS grid collapse properly when the interpretations panel is toggled, the container of highchart must be absolute positioned.
This caused a minor overflow problem where the legend of the chart was outside the parents' container boundary. That was due to the container having also the TitleBar component.
To solve the problem I added a new grid cell for the TitleBar.
Then the grid-gap was showing a line below the TitleBar also when there was no title.
By replacing grid-gap with the required border rules for the various cells, the undesired lines are removed.
> CSS grid fixes

- packages/app/config/webpack.config.dev.js
- packages/app/config/webpack.config.prod.js
- packages/app/package.json
- yarn.lock
[DHIS2-5108]
- include react and react-dom in the webpack bundle
- upgrade runtime dependencies
***********************
It has been decided that apps will reduce their dependence on the web-core-resources and start to bundle all their dependencies. This at least makes sense for react and react-dom, where the improvement in download bandwidth is negligible since apps are all using different versions of react anyway.
Changes to bundle size:
react: 5 KB parsed
react-dom 96 KB parsed (4% of total bundle size)
For comparison, the data visualizer bundle currently has the following:
@material-ui/core: 227 KB parsed
material-ui (0.20): 384 KB parsed.
Hopefully, with the next major release of the d2-ui components, we will be able to remove the material-ui dependency, so the …
> task/bundle react and react-dom

- jest.config.js
- packages/app/package.json
- packages/app/src/components/Dimensions/DimensionList.js
- packages/app/src/modules/current.js
- yarn.lock
Upgrade to the latest d2-ui package version. With the latest version we significantly reduce the data visualizer bundle size (reduced by 15%), due to improved treeshaking.
Since d2-ui no longer comes with a commonjs build, it is necessary for jest to transform d2-ui code. Therefore the addition to the transformIgnorePatterns in the jest config.
A couple of prettier fixes (not sure where those errors came from)
> task/upgrade d2-ui packages and add transformIgnorePattern for jest

- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/components/App.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/settings.js
- packages/app/src/reducers/ui.js
Bug was introduced where clear_ui reducer expected an argument, but not all action calls provided the argument
> fix/make sure root org unit and relative period are sent to clear_ui reducer

- packages/app/src/components/Dimensions/Dialogs/OrgUnitSelector/OrgUnitDimension.js
This PR includes:
- Fix for displaying selected org units counter in org units chip
> Use name or displayName for org units in metadata

- packages/app/src/components/Dimensions/Dialogs/DataDimension/DataDimension.js
- packages/app/src/components/Dimensions/Dialogs/DialogManager.js
- packages/app/src/components/Dimensions/Dialogs/DynamicDimension/DynamicDimension.js
- packages/app/src/components/Dimensions/Dialogs/OrgUnitDimension/OrgUnitDimension.js
- packages/app/src/components/Dimensions/Dialogs/OrgUnitDimension/__tests__/OrgUnitDimension.spec.js
- packages/app/src/components/Dimensions/DimensionLabel.js
- packages/app/src/components/Dimensions/DimensionOptions.js
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/Tooltip.js
- packages/app/src/components/Layout/__tests__/Tooltip.spec.js
- packages/app/src/reducers/ui.js
In OrgUnitDimension, get only the properties actually needed
In the other files, use empty array from a variable as default, rather than [], which is a new reference and will trigger an update every time.
> chore/reduce component re-renders by optimizing gets from store

- packages/app/src/components/Visualization/BlankCanvas.js
The error in IE11 was a DOM not found error.
My explanation is that the LoadingMask component was removed when
Highcharts replaces the content of the div with the chart.
React/IE11 does not seem to like that.
Solution is to put the LoadingMask component outside the div used by
Highcharts, LoadingMask is still controlled by the loading state prop.
> DHIS2-5281: fix problem with LoadingMask which prevented chart to load

- packages/app/src/components/Dimensions/Dialogs/styles/buttons.style.js
This PR includes setting height, and minHeight (redundant) to the select / deselect buttons.
I inspected the element in IE11, minHeight is not registered.
It is sufficient with only specifying height /width but to be sure i left the minHeight/ minWidth value in there.
> Fix/select deselect buttons in IE11

- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
Gives each process (by process I mean everything that happens from the update button is clicked to the chart is rendered) an id. When a process starts we keep this id as the renderId (active id). Then in the middle of the process we check if the process id is still the active id or if it has been replaced by a new process. We check that three places:
- before fetching analytics data from the server
- before rendering the chart
- before showing an error message if the server request failed
If the process id is no longer the active id we cancel the process so that is doesn't conflict with the new process or do unnecessary work/server requests.
> Cancel requests

- packages/app/package.json
- packages/app/src/index.js
- yarn.lock
In IE, opening a file from the file->menu crashes. This was due to URLSearchParams not being supported in IE. Solution was to add the url-polyfill. Note that URLSearchParams is not actually in the File-menu component. It is in the data-visualizer DownloadMenu component.
url-polyfill is used in maps-app to solve the same problem.
> fix/add url-polyfill for URLSearchParams

- packages/app/src/components/Layout/styles/Menu.style.js
This PR includes:
adding style
```
background: 'none'
```
to the Layout's IconButton  in order to remove hover effect on the MoreHorizontalIcon for selected dimensions.
> fix/hover-effect-selected-dimensions [DHIS2-5266]

- packages/app/i18n/en.pot
- packages/app/src/components/Dimensions/Dialogs/OrgUnitDimension/OrgUnitDimension.js
This PR includes bug-fix for org units dimension.
Steps to reproduce (do not refresh the page during the process):
1) Open AO with preselected org units (multiple levels)
2) Open org units dimension dialog
3) Open another AO
4) Open org units dimension dialog again
5) Previously expanded org units are not selected anymore, but they are still expanded
Correct behaviour - only selected org units should be expanded.
I had a discussion with @joeDHIS about keeping org units expanded during opening/closing the dialog.
Although it is not the exact use case, the main idea was that whenever user chooses some org units and then clicks "deselect all" or reopens the dialog, org units should stay expanded (so that user wouldn't have to expand them again) even if they are not selected.
This applies …
> Subscribe to analytic object id to remount org units selector

- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/components/App.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
- packages/app/src/components/__tests__/App.spec.js
- packages/app/src/modules/fields/baseFields.js
- packages/app/src/modules/fields/nestedFields.js
- packages/app/src/reducers/visualization.js
- fetch interpretations fields id and created
- avoid unnecessary analytics request and chart recreation
(cherry picked from commit b4fd6d5fa0619d30e96cc70d210166e1ab8cea53)
> DHIS2-5434: fix flashing chart when loading interpretation directly from URL (#168)

- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
This is to avoid flashing of the chart in dashboard.
The change allows for the config object to have several keys, but still
fetch the chart by id as the config object passed from dashboard to the
plugin is a stripped down version of the AO and does not have the
necessary data for generating the chart without fetching it.
> Fetch chart always by id when used in dashboard

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
- packages/plugin/src/api/analytics.js
- packages/plugin/src/api/visualization.js
- packages/plugin/src/modules/analytics.js
- packages/plugin/src/modules/chartTypes.js
- packages/plugin/src/modules/fields/baseFields.js
- packages/plugin/src/modules/fields/index.js
- packages/plugin/src/modules/fields/nestedFields.js
- packages/plugin/src/modules/options.js
- packages/plugin/src/widgets/LoadingMask.js
- yarn.lock
This reverts commit eecfea0dd13e7620e0dd5c1f104e8aba0a3b5505.
The code-sharing solution does not work when the plugin is pulled in as a dependency in other apps (e.g., dashboards), since imports like:
`import { apiFetchVisualization } from 'data-visualizer-app/src/api/visualization';`
don't exist in dashboards. This code will have to remain duplicated until we are ready with a published, shared library.
> Revert "fix: use lerna to share code instead of copying resources (#214)

- packages/app/src/components/DimensionsPanel/Dialogs/OrgUnitDimension/OrgUnitDimension.js
- packages/app/src/modules/__tests__/currentAnalyticalObject.spec.js
- packages/app/src/modules/__tests__/orgUnitDimension.spec.js
- packages/app/src/modules/__tests__/ui.spec.js
- packages/app/src/modules/currentAnalyticalObject.js
- packages/app/src/modules/orgUnitDimensions.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
Relates to [DHIS2-5987](https://jira.dhis2.org/browse/DHIS2-5987).
This PR covers some edge cases for "Open as map" feature and contains:
- Fix for generating correct paths for `ou` dimension items (with `/` prefix) and supplying them to current analytical object in user data store
- Fix for generating correct parentGraphMap *from* current analytical object
- Fix for generating complete correct parentGraphMap *for* current analytical object
- Fix for generating correct parentGraphMap value for root organisation unit upon orgunit selection in `OrgUnitDimension` dialog.
- Tests
P.s. I had to reimplement `removeLastPathSegment` function which was earlier imported from `@dhis2/d2-ui-org-unit-dialog` component, since importing causes circular dependency error (presumably coming from d2).
> Append correct paths for org units

- packages/app/src/components/Visualization/Visualization.js
- packages/plugin/package.json
- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
- packages/plugin/src/api/analytics.js
- packages/plugin/src/api/visualization.js
The plugin should get d2 as a property rather than having its own version, as the app should determine which version of d2 to use.
> Provide d2 as a prop rather than being a dependency

- packages/app/package.json
- yarn.lock
Fixes [DHIS2-6359](https://jira.dhis2.org/browse/DHIS2-6359)
Problem:
In data visualizer app > sharing dialog > the metadata write / read dialog - this looks a bit cramped together vs the UI we have e.g. in the maintenance app.
Proposal:
Make the visualizer dialog a bit more spacious similar to maintenance dialog.
perhaps this is about upgrading the component.
Solution:
1) Use material ui `MenuList` component to enable correct paddings in sharing component.
2) Update FileMenu component to include updated sharing component
3) Update FileMenu component version in Data Visualizer app.
Before fix:
After fix:
> fix: Update file menu version to apply correct styles in sharing dialog access options

- packages/app/package.json
- yarn.lock
Fixes [DHIS2-6359](https://jira.dhis2.org/browse/DHIS2-6359)
Problem:
In data visualizer app > sharing dialog > the metadata write / read dialog - this looks a bit cramped together vs the UI we have e.g. in the maintenance app.
Proposal:
Make the visualizer dialog a bit more spacious similar to maintenance dialog.
perhaps this is about upgrading the component.
Solution:
1) Use material ui `MenuList` component to enable correct paddings in sharing component.
2) Update FileMenu component to include updated sharing component
3) Update FileMenu component version in Data Visualizer app.
Before fix:
After fix:
> fix: Backport (v31) - update file menu version to apply correct styles in sharing dialog access options

- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
Pass required d2 prop to `apiFetchAnalyticsForYearOverYear` function in plugin
> fix: Fetching analytics for year over year charts in plugin

- packages/plugin/src/ChartPlugin.js
When we pass full analytical to the plugin without `aggregationType` property specified, it passes it to analytics request.
As a result we have request like this:
_localhost:8080/api/29/analytics.json?dimension=dx:ntzmpYRSKGg&dimension=ou:ImspTQPwCqd;LEVEL-3&filter=pe:2018&**aggregationType=undefined**&skipMeta=false&skipData=true&includeMetadataDetails=true_
This request returns 500 server error.
Removing `aggregationType=undefined` from analytics URL makes request correct and it returns correct response. 
To fix this we can check if option value (e.g. aggregationType) is undefined and if it is - check if defaultValue is/can be undefined. If the answer to both questions is yes, then assume we can assign undefined to option value, otherwise skip assigning (see files changed).
> fix: Fetching analytics for analytical object with undefined aggregationType in plugin

- packages/app/public/index.html
See https://jira.dhis2.org/browse/DHIS2-6122.
From my comment in the Jira-issue: 
> This bug only seem to affect Chrome. The reason is that chrome does not seem to send credential-headers or cookies for 'rel=manifest' attributes on the link-tag, even for same origin requests. This means that the server responds with a 302-redirect to the login-page, and the browser tries to parse this as JSON, which fails since its html (the login page).
The solution is to add the attribute `crossorigin='use-credentials'`/ to the manifest-link-tag.
See https://github.com/w3c/manifest/issues/186#issuecomment-43939505 and https://github.com/w3c/manifest/issues/535#issuecomment-435739223 for discussion about this weird behaviour.
> fix: manifest credentials bug in chrome

- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
In the other cases always use the config object directly.
This is to allow dashboards to set filters directly on the AO.
> Fetch vis by id only when passed config contains only id

- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/__snapshots__/DialogManager.spec.js.snap
- packages/shared/src/components/ItemSelector/__tests__/SelectedItems.spec.js
* generate and check snapshots for DataDimension component
* removed a few ItemSelector tests as the ItemSelector component is being moved to a different repo, so test fixes/changes will not be dealt with here
> chore: generate missing snapshots for tests

- packages/app/src/components/App.css
- packages/app/src/components/App.js
Fixes issue where the css for the apps in the headerbar app menu was messed up (had extremely big height and wrong bg color)
> chore: use specific app class instead of generic 'app' to prevent side effects

- packages/app/src/components/Layout/Menu.js
Fixes [DHIS2-6611](https://jira.dhis2.org/browse/DHIS2-6611).
**Problem**
Context menu doesn't close after mouse click on "Manage axes" menu item.
Clicking on other menu items ("Move to category", "Move to filter" and "Remove") "closes" menu, but under the hood it just removes chip & menu entirely, therefore the problem was unnoticeable before introducing "Manage axes" menu item.
**Solution**
Close menu programmatically after mouse click on menu item.
**Implementation**
Since we generate menu items in `DefaultAxis` component and pass them as props to `Chip` which renders `Menu` - we don't have control over `Menu` in `DefaultAxis` component.
To solve this without changing current architecture we can use React built-in `cloneElement` function and assign one more `onClick` callback function …
> fix: Close context menu on item click in Chip component

- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
Fixes include:
* call "Set" instead of "Add" since the returned list contains the complete selected list
* check that ou.path exists before acting on it. In the case of user org units, path does not exist, which resulted in the app crashing
To reproduce the org unit bug:
1. Open the OrgUnit Dimension
2. Select one or more of the User org unit checkboxes. The app will crash.
> fix: only act on path if it exists

- packages/plugin/src/ChartPlugin.js
Fixes [DHIS2-6597](https://jira.dhis2.org/browse/DHIS2-6597).
Chart items re-render in dashboards app even if props stay the same (triggers by editing text item).
Use `lodash/isEqual` function to check equality of props (config & filter) to determine if component should re-render the chart.
> fix: Use deep equality check for plugin props on componentDidUpdate to avoid unnecessary updates

- packages/plugin/src/ChartPlugin.js
The style prop seems to change when a dashboard item is resize, and
can be used for triggering recreateChart() which also disables chart
animation.
Related to DHIS2-6597.
> fix: dashboard items resize should trigger chart reload

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
New version of DV plugin published v32.0.6 and DV app uses it.
> chore(v32): update dv plugin

- packages/app/src/components/AxisSetup/AxisSetup.js
- packages/app/src/components/AxisSetup/styles/AxisSetup.style.js
Fixes [DHIS2-6625](https://jira.dhis2.org/browse/DHIS2-6625).
**Problem**
Line-height on paragraph text in the Manage axes dialog is too low, making it slightly hard to read.
**Solution**
Apply `line-height: 1.5` css rule to dialog's help text block.
> chore: Make axis dialog help text more readable with increased line height (1.5)

- packages/plugin/package.json
- yarn.lock
Relates to [DHIS2-6989](https://jira.dhis2.org/browse/DHIS2-6989).
- Upgrading `d2-charts-api` version to 33.0.0 to move title to top for gauge chart type
> chore: Upgrade d2-charts-api to move gauge title to top

- packages/app/package.json
- yarn.lock
Backport to v31. Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250)
> chore(v31): update interpretations panel [DHIS2-6250]

- package.json
- packages/app/i18n/en.pot
- packages/app/package.json
- yarn.lock
Backport to v32. Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250)
> chore(v32): update interpretations panel [DHIS2-6250]

- packages/app/package.json
- packages/app/src/api/analytics.js
- packages/app/src/components/DimensionsPanel/Dialogs/AddToLayoutButton/AddToLayoutButton.js
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/DimensionsPanel/__tests__/DimensionsPanel.spec.js
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/PieLayout/PieLayout.js
- packages/app/src/components/Layout/YearOverYearLayout/YearOverYearLayout.js
- packages/app/src/index.js
- packages/app/src/modules/__tests__/current.spec.js
- packages/app/src/modules/__tests__/layoutAdapters.spec.js
- packages/app/src/modules/current.js
- packages/app/src/modules/currentAnalyticalObject.js
- packages/app/src/modules/layout.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/layoutValidation.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/__tests__/current.spec.js
- packages/app/src/reducers/__tests__/dimensions.spec.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/dimensions.js
- packages/app/src/reducers/ui.js
- packages/plugin/package.json
- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
- yarn.lock
I left the `d2-utilizr` dependency for now, but we might want to replace that with lodash or other, since we are not using it in DV for similar purposes.
> refactor(): use @dhis2/analytics in place of @dhis2/d2-ui-analytics

- packages/plugin/package.json
- yarn.lock
Relates to [DHIS2-6983](https://jira.dhis2.org/browse/DHIS2-6983).
- Updating `@dhis2/analytics` dependency to v2.3.0 to enable epi weekly periods.
> chore: update @dhis2/analytics to enable epi weekly periods

- packages/app/src/reducers/index.js
> Warning: Failed prop type: The prop `items[0].name` is
marked as required in `AxisSetup`, but its value is `undefined`.
>    in AxisSetup (created by WithStyles(AxisSetup))
was sometimes popping up and it turned out sometimes there is no name
available in the metadata for the item object.
Changed the code to initialize the name to empty string when not
available instead of passing undefined.
> fix: avoid React warning about required proptype

- packages/app/package.json
- yarn.lock
Updated d2-ui-interpretations dependency to avoid missing parsing of
*bold* and _italic_ text when directly followed by a :
DHIS2-7249.
> fix: allow : after bold and italic

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/App.css
- packages/app/src/components/App.js
- packages/app/src/components/UpdateButton/UpdateButton.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
- packages/app/src/components/__tests__/App.spec.js
- packages/app/src/modules/current.js
- packages/app/src/reducers/current.js
- packages/plugin/package.json
- yarn.lock
Backports the latest work on single value charts.
> fix: backport latest single value fixes in master

- packages/app/src/components/App.css
- packages/app/src/components/App.js
There was a missing flexbox rule that messed up the layout when interpretations panel was shown.
Also changing the main-right (interpretation panel area) background color slightly because there was no visible separation vs main-center (chart area) for SV charts when interpretations panel was shown.
> fix: viewport layout with visible interpretations panel

- packages/app/i18n/en.pot
- packages/app/src/components/App.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeIcon.js
- packages/app/src/index.js
- packages/app/src/modules/chartTypes.js
- packages/app/src/reducers/ui.js
- packages/plugin/src/PivotPlugin.js
- packages/plugin/src/index.js
- packages/plugin/src/modules/chartTypes.js
- Adds a new visualization type for Pivot table.
- FileMenu lists `reportTable` AOs when the pivot type is selected (temporary solution for testing purposes when a proper plugin for pivot is available).
There is a problem with this in subsequent vis type changes as FileMenu does not refresh the list of files when the `fileType` passed changes (needs to be fixed in the d2-ui component)
- Currently the pivot plugin is just a copy of the chart one.
- The pivot type is now also the default vis type; this is to avoid problems due to the missing `type` in the reportTable AO.
This allows to open a pivot table directly via URL and have the correct type and plugin used.
DHIS2-7721.
> feat: WIP pivot table type

- packages/app/src/components/Layout/DefaultLayout/styles/DefaultLayout.style.js
When adding multiple filter dimensions that creates three or more filter rows the vertical scaling breaks the layout, causing the name of the chart to overflow into the axes area.
> fix: vertical scaling with >= 3 filter rows (DHIS2-7802)

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/AddToLayoutButton/AddToLayoutButton.js
- packages/app/src/components/DimensionsPanel/Dialogs/AddToLayoutButton/__tests__/AddToLayoutButton.spec.js
- packages/app/src/components/DimensionsPanel/Dialogs/AddToLayoutButton/__tests__/Menu.spec.js
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/DefaultLayout/DefaultLayout.js
- packages/app/src/components/Layout/Menu.js
- packages/app/src/components/Layout/PieLayout/PieLayout.js
- packages/app/src/components/Layout/YearOverYearLayout/YearOverYearAxis.js
- packages/app/src/components/Layout/YearOverYearLayout/YearOverYearLayout.js
- packages/app/src/modules/__tests__/current.spec.js
- packages/app/src/modules/__tests__/layoutAdapters.spec.js
- packages/app/src/modules/current.js
- packages/app/src/modules/currentAnalyticalObject.js
- packages/app/src/modules/layout.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/layoutValidation.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
- packages/plugin/package.json
- yarn.lock
DO NOT MERGE, depends on https://github.com/dhis2/analytics/pull/153
Use renamed constants (axis name -> axis id) from analytics.
> fix: rename axis name constants

- .huskyrc.js
- .prettierignore
- package.json
↔️ Follows the [pattern from Dashboards](https://github.com/dhis2/dashboards-app/pull/520)
🎉 Adds commit hooks using [cli-style](https://github.com/dhis2/cli-style) and Husky 💻 🚀 
🔨 Before commit, the following will be run and validated:
1. JS code using `d2-style js check --staged`
1. Text using `d2-style text check --staged`
1. Commit message
🔨 Before push, the following will be run and validated:
1. Test suite
💡  A _dry run_ of the commit validation can be run using `yarn validate-commit`.
💡  A _dry run_ of the push validation can be run using `yarn validate-push`.
> fix: cli-style commit hooks

- packages/app/package.json
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/DefaultLayout/styles/DefaultAxis.style.js
- packages/app/src/components/Layout/Layout.js
- yarn.lock
This adds drag 'n drop capabilities to the dimension Chip components in
the Layout, allowing for reordering of the dimensions within an axis.
This is required for PT where the order is reflected in the generated
table.
DHIS2-7939.
> feat: drag 'n drop for reordering dimension items in layout

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Required to support changes in the AO format
> chore: bump analytics version to 2.7.2

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/LegendDisplayStrategy.js
- packages/app/src/components/VisualizationOptions/Options/LegendSet.js
- packages/app/src/modules/fields/nestedFields.js
- packages/app/src/modules/options.js
- packages/app/src/modules/options/pivotTableConfig.js
- packages/plugin/package.json
- yarn.lock
It seems backend support for having multiple legends by data element in a visualization object is not in place.
The implementation in this PR is then the same as the current one used in PT app.
I guess we can merge this version to start with, while the backend support is added.
I'm not sure if that feature/improvement for legendSet is supposed to be in place for 2.34.
Labelling as WIP until I tested it a bit more and I figure out what's the plan for the multiple legend by data element feature/improvement.
Cfr. Joe's sketch: https://sketch.cloud/s/boZO0/a/zOyWPy/play (click Options -> Legend -> Assign a unique legend to data elements).
> refactor: components for legendSet and legendDisplayStrategy options

- packages/app/src/components/VisualizationOptions/Options/RadioBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/SelectBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/SortOrder.js
- packages/app/src/modules/options.js
This PR fixes the issue of options with numerical values not working correctly.
Specifically, sortOrder, which has been also refactored to remove the None value in the select, since the checkbox already can tell if there is no sort order (option off).
The select then has only the 2 values for "low to high" and "high to low".
When the option is enabled via the checkboxes, "low to high" is preselected effectively changing the option value in the ui.
> fix: options with numeric values (sortOrder)

- packages/app/package.json
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/modules/layout.js
- packages/app/src/reducers/ui.js
- packages/plugin/package.json
- yarn.lock
When source and destination axis change during a DND move the `acAddUiLayoutDimensions` action is called which runs the layout rules validation.
When source and destination axis remains the same it means it's a reordering and `acSetUiLayout` is used instead (which does not run the layout rules validation).
There is a problem with SV when dragging a dimension in the Series axis, the Data dimension is moved to filters and the dragged dimension drops in Series.
The Data dimension in SV is a locked dimension, so it should not happen.
Requires this PR to be merged first: https://github.com/dhis2/analytics/pull/253
> fix: fixes for DND between axes

- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/DefaultLayout/styles/DefaultAxis.style.js
Solves the issue with chip showing a `grab` cursor on its border that was caused by RB-DnD
> fix: chip cursor

- packages/app/src/api/dataStatistics.js
It worked on localhost, but not in production. Removing the base url.
> fix: post data stats url

- packages/app/src/api/dataStatistics.js
It worked on localhost, but not in production. Removing the base url.
> fix: remove api.baseUrl duplicate

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Layout/PivotTableLayout/PivotTableLayout.js
- packages/app/src/components/Layout/PivotTableLayout/styles/PivotTableLayout.style.js
- packages/plugin/package.json
- yarn.lock
HOLD MERGE: depends on https://github.com/dhis2/analytics/pull/263.
Adds a specific layout for pivot tables. Reusing default axes and styles where possible.
> fix: layout for pivot tables

- packages/app/src/components/VisualizationOptions/Options/TopLimit.js
They are numeric values, not strings.
> fix: fix values for topLimit option

- packages/app/src/components/VisualizationOptions/Options/RangeAxisDecimals.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisSteps.js
- packages/app/src/components/VisualizationOptions/styles/VisualizationOptions.style.js
some minor changes to the options dialog to make sections easier to parse:
- adjusted font size/weight for section headings
- adjusting padding/margins between sections
- added bottom border to paddings
while I'm here:
- adjusted 'axis decimals' and 'axis steps' inputs to be wider to accomodate placeholder text
> fix: adjust options dialog for easier scanning

- packages/app/src/components/App.js
- packages/app/src/components/DimensionsPanel/DndDimensionList.js
- packages/app/src/components/DimensionsPanel/DndDimensionsPanel.js
- packages/app/src/components/DimensionsPanel/styles/DndDimensionList.module.css
- packages/app/src/components/DimensionsPanel/styles/DndDimensionsPanel.module.css
* Divides the Dimension Panel in to sections in accordance to the new design, with "Main", "Other" and "Your" dimensions.
* Style update for the dimensions search at the top
> fix: dimensions panel divided in to sections

- packages/app/src/components/VisualizationOptions/Options/AggregationType.js
- packages/app/src/components/VisualizationOptions/Options/DigitGroupSeparator.js
- packages/app/src/components/VisualizationOptions/Options/DisplayDensity.js
- packages/app/src/components/VisualizationOptions/Options/FontSize.js
- packages/app/src/components/VisualizationOptions/Options/HideEmptyRowItems.js
- packages/app/src/components/VisualizationOptions/Options/LegendSet.js
- packages/app/src/components/VisualizationOptions/Options/NumberType.js
- packages/app/src/components/VisualizationOptions/Options/RegressionType.js
- packages/app/src/components/VisualizationOptions/Options/SelectBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/SortOrder.js
- packages/app/src/components/VisualizationOptions/Options/TopLimit.js
- packages/app/src/components/VisualizationOptions/__tests__/SelectBaseOption.spec.js
- packages/app/src/modules/current.js
- packages/app/src/modules/options.js
The toggleable Select is now assuming the default/disabled value for the option is mapped to the unchecked state of the Checkbox, while the other options are listed in the Select that shows when the Checkbox is checked.
Numeric values for options coming from the api do not play well with ui-core Select components.
Only strings are allowed for the option values.
We should be able to use`ui` in the Redux store directly in the UI components, the conversions must then happen before writing and after reading the options from the visualization object.
> fix: fixes for options with numeric values and toggleable Select

- packages/app/src/modules/__tests__/layoutAdapters.spec.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/ui.js
The adapted layout should be used always when changing vis type, also
for the "default" vis types.
> fix: properly set layout on vis type change for all vis types

- packages/app/src/modules/ui.js
Catch pivot tables so they are not run through the default adapter.
> fix: do not run default adapter for pivot tables

- packages/app/src/components/VisualizationOptions/Options/ShowDimensionLabels.js
This was probably a typo - the correct option is `showDimensionLabels`
> fix: correctly set showDimensionLabels option

- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
When adding a dimension through the dimension panel context menu, the dimension modal should open if the dimension doesn't have any items selected. Previously, probably because of a typo, the modal would _only_ open for dimensions _with_ items 🤷‍♂ This has now been fixed.
> fix: open modal for empty dims 

- packages/plugin/src/PivotPlugin.js
This fixes an error thrown if Pivot Table is rendered without a valid `visualization` or `data` prop.
> fix: don't render pivot table before data has loaded

- packages/app/src/components/VisualizationOptions/Options/HideSubtitle.js
- packages/app/src/components/VisualizationOptions/Options/HideTitle.js
Also fixed the subtitle option to work in the same way as the title.
Before when no custom subtitle was specified, the Custom subtitle was
selected with an empty value.
Now Auto means not hidden subtitle but also not custom subtitle.
The subtitle is actually auto generated in some situations (depending on
vis type, presence of title...)
> fix: remove custom title when Auto is selected (DHIS2-8252)

- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/Visualization.spec.js
- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/PivotPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
- packages/plugin/src/index.js
Currently there's a prop on `Visualization.js` called `visConfig`, which is passed to the plugins as `config`. This name is a legacy from https://github.com/dhis2/data-visualizer-app/commit/af1d0124b0338f0114b9a59fbbc2e500175ba227#diff-e4a1f1987c1f3a83a3ed17722cecb3a4 but has later evolved to contain either `state.visualization` or `state.current`. This PR renames the prop to a more understandable name (currently `visualization`, but that's open for suggestions).
> refactor: rename visConfig and config

- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
This solves https://jira.dhis2.org/browse/DHIS2-8290 and supercedes #637 - it should work for no-op updates as well as loading saved AOs, changing chart types, and resizing the browser window.
More eyes (on code and testing the app) would be great - it should be functionally equivalent to the previous class Component, but a bit more explicit and clear about what happens when, and with the above bugs fixed, but it's still a fair number of changed lines
> fix: avoid infinite loading and make chart plugin use hooks (DHIS2-8290)

- .github/workflows/node-lint.yml
- .github/workflows/node-publish.yml
- .github/workflows/node-test.yml
- packages/app/package.json
- packages/plugin/package.json
We will use Travis for running the deploy-build script to d2-ci ([more information on why](https://developers.dhis2.org/2019/02/the-build-system/#d2-ci-organisation)) and our more _modern_ tooling for NPM until we've ported the deploy-build script.
> chore(github-actions): add workflows for lint and publish

- .github/workflows/node-lint.yml
- .github/workflows/node-publish.yml
- .github/workflows/node-test.yml
- lerna.json
We need to build the plugin before testing, otherwise the plugin's entrypoint (`build/es/lib.js`) doesn't exist and can't be resolved through the workspaces link.
This also removes the extraneous `lerna.json`
> chore: fix GitHub Actions test workflow

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
This moves plugin `react` and `react-dom` deps to Peer, and moves app deps from `peer` to `runtime` (technically they could be omitted, but we're going for explicit here).  While it shouldn't technically be required to specify `react` as a peer dep in the plugin (`yarn` should de-duplicate if the major version matches) it makes sense to ensure that there can only be one copy.  This will also cut version 34.0.0.
BREAKING CHANGE: The Data Visualizer Plugin now requires `react` and `react-dom` to be provided by the consumer.
> fix: correctly specify runtime and peer dependencies

- packages/app/src/components/VisualizationOptions/Options/LegendSet.js
- packages/app/src/modules/options.js
The selection for Legend type was lost when switching between tabs,
causing the app to crash.
The reason was that the radio group had no default value (which does not make sense for a radio group).
`FIXED` should be the default value for `legendDisplayStrategy`, which enables the dropdown for the selection of the legendSet.
Use a constant for the option name and get the default value from the
options list.
Moved also the query to the top.
> fix: fix default state for LegendSet option

- packages/app/src/modules/visualization.js
This was causing all options to be removed from the object passed in the
POST when saving.
> fix: fix filtering of non savable options

- packages/app/src/components/Visualization/Visualization.js
There's a bug which causes YearOverYear vis types to incorrectly display "no data" when one year is missing data but other years have data that can still be shown.
The bug was introduced in https://github.com/dhis2/data-visualizer-app/pull/552 by https://github.com/dhis2/data-visualizer-app/blob/14644ad38fdd50c533bda2c512db289d28b08d3e/packages/app/src/components/Visualization/Visualization.js#L66
**Previously**: "This year" has data but "2011" doesn't, incorrectly displays "No data" for the whole visualisation
**Fix**: "This year" has data but "2011" doesn't, correctly displays the data for "This year" and disregards the missing data for "2011"
> fix: YoY displays "no data" when some years actually have data (but some don't)

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/modules/options/gaugeConfig.js
- packages/plugin/package.json
- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/__tests__/ChartPlugin.spec.js
- yarn.lock
1. Adds legends to Gauge options
2. Sends through `legendSets` to Analytics for the visualization generation.
3. Updates the Analytics dep
Depends on https://github.com/dhis2/analytics/pull/315/
> fix: legends for gauge

- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/Legend.js
- packages/app/src/modules/options/config.js
- packages/app/src/modules/options/singleValueConfig.js
- packages/plugin/package.json
- yarn.lock
Adds Single Value legend options. Since SV can only change the text color, the "style" option thats present for other visualisation types has been hidden.
https://jira.dhis2.org/browse/DHIS2-8348
Depends on https://github.com/dhis2/analytics/pull/320
> fix: single value legend (DHIS2-8348)

- packages/app/package.json
- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/columnConfig.js
- packages/app/src/modules/options/gaugeConfig.js
- packages/app/src/modules/options/lineConfig.js
- packages/app/src/modules/options/pieConfig.js
- packages/app/src/modules/options/singleValueConfig.js
- packages/app/src/modules/options/stackedColumnConfig.js
- packages/plugin/package.json
- yarn.lock
Adds the `completedOnly` option to all vis types
> fix: completed only all vis types

- packages/app/i18n/en.pot
- packages/app/src/api/analytics.js
- packages/app/src/components/VisualizationOptions/DataTab.js
- packages/app/src/components/VisualizationOptions/Options/CompletedOnly.js
- packages/app/src/components/VisualizationOptions/__tests__/DataTab.spec.js
* Adds the `completedOnly` option to the option modal, api requests and data download
> fix: added completedOnly to all vis types

- packages/app/src/modules/current.js
Only cast the value for numeric options if it's defined.
This prevents those options to passed around with NaN as value.
undefined is the default value, and is now passed around as is.
> fix: avoid casting undefined to Number -> NaN

- packages/app/src/components/VisualizationOptions/Options/LegendDisplayStrategy.js
Use consistent terminology for legends.
Users don't understand what a "legend set" is.
> fix: rephrase legend display strategy option

- packages/app/i18n/en.pot
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/modules/error.js
- packages/app/src/modules/layoutValidation.js
Data element group set dimension items should be allowed to be used without a data dimension item. Solution: 
* Removes the data dimension validation from layout validation (front end) and catches the old api error (screenshot) to display the new data dimension error again.
* Updates the error message to include info about data element group sets (verified with @cooper-joe )
* YearOverYear, Gauge and Single Value still requires Data
Affects the testing of https://jira.dhis2.org/browse/DHIS2-5029, but the end result for the user should be unaffected.
Old error
New error
> fix: remove data dimension validation

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/PivotPlugin.js
- yarn.lock
The actual fix is released in [`@dhis2/analytics@4.3.2`](https://github.com/dhis2/analytics/pull/332).
Basically when the interpretations button is toggled, the dimensions of the parent container of the pivot table are reset to 0.
This seems to allow the flow applied to the right section of the app to work and the interpretations panel is shown.
The observer attached on the pivot table plugin container then triggers and calculates and applies its correct dimensions.
> fix: interpretations panel show for PT visualization type DHIS2-8300

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
In the data visualizer app, for the org unit dimension selector dialog, for the org unit tree. Currently there is a function for selecting all org unit children which is accessed by right-clicking on an org unit. Ticket: https://jira.dhis2.org/browse/DHIS2-6562
This function is labelled "Select children", but should rather be: "Select all org units below".
Bump analytics to v4.3.4 (https://github.com/dhis2/analytics/pull/337) which bumps d2-ui-org-unit-dialog to v6.5.9, which contains dhis2/d2-ui#573 that changes the name of the label.
Fixed:
> fix: bump @dhis2/analytics@4.3.4 to fix DHIS2-6562

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
This supports adaptive sizing of Pivot Table columns for any size table, while still clipping the DOM footprint of all tables.
> fix: support adaptive clipping for pivot tables

- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/modules/error.js
During the 2.34 dev demo @larshelge collected user-feedback regarding the text for the "No data" and "No period" messages. It was also noted that the start message incorrectly told the user to "double click" a dimension. These messages have now been updated.
--------------
Original feedback:
> "No data set": This is a bit confusing, i thought it referred to a "dataset". We could say "No data items selected".
Replace "set" with "selected", so "No period set" -> "No periods selected".
--------------
Updated "No data" message:
--------------
Updated "No period" message
--------------
Updated start page message:
> fix: updated the error and start page texts based on user feedback

- packages/app/src/modules/options.js
- packages/plugin/src/modules/options.js
`hideEmptyRows` and `hideEmptyColumns` options are only intended for the
analytics download request when `tableLayout` is passed (download .xls, .csv and .html+css for PT), not for the normal request used to render the table.
Passing them does not affect the response payload, but does negatively affect caching, both client and server side, because the options are passed in the query string.
Solution is to mark them as non-requestable in the options list config file.
The URLs used in the download menu do not look at this flag, but rely only on the options been set in the visualization object (`current` in the app's Redux store).
Fixes: https://jira.dhis2.org/browse/DHIS2-8401.
Note: the changes in `options.js` for plugin related to `legendDisplayStrategy` and `legend` are there just to …
> fix: do not use options intended for download request DHIS2-8401

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Upgrades to Analytics v4.3.8 (https://github.com/dhis2/analytics/pull/340) for adding ellipsis to long Highcharts titles.
------------------
Example:
> fix: upgrade to Analytics v4.3.8 for title ellipsis

- packages/app/package.json
- yarn.lock
Upgrades `d2-ui-file-menu` to v6.5.10 (https://github.com/dhis2/d2-ui/pull/574).
Implement the new design for the filter by visualization type in the File Open dialog.
- "Chart" and "Pivot Table" are at the top of the list.
- "Chart" comprises of all chart types, basically all the types listed except "Pivot Table".
> fix: d2-ui-file-menu v6.5.10, improved open dialog organisation (DHIS2-8413)

- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/components/App.js
Currently, when trying to Save or Save As on a "dirty" AO (i.e. a previously saved AO that has been updated), the _Discard unsaved changes?_ modal would incorrectly trigger when the save had been done. 
To recreate: Open a saved AO. Do any change and click Update. The AO is now "dirty". Click File -> Save or Save As. Just before the AO refreshes the modal will be shown (incorrect).
This PR prevents the modal from being displayed by passing a param on the `history` object called `isSaving`, which is used to prevent the modal. 
-------
_Discard unsaved changes?_ modal for reference
> fix: saving incorrectly shows the confirmation 

- packages/app/src/components/Layout/Tooltip.js
Fixes proper display names for ou levels/groups in dimension chip tooltip.
Before:
After:
> fix: show names for levels and groups in dimension chip tooltip

- packages/plugin/src/api/analytics.js
Check the type of the passed in visualization object. Only request "includeNumDen" for pivot tables.
> fix: only request numDen for pivot tables

- packages/app/src/components/ErrorBoundaries/FatalErrorBoundary.js
- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/modules/error.js
Noticed that there was three identical copies of a generic error title "something went wrong", so I consolidated all three to a const that already existed in the error file, to be used by all: https://github.com/dhis2/data-visualizer-app/blob/ea7c1cc9550e43fbe41319ca7672758c7db25f37/packages/app/src/modules/error.js#L247
(NOJIRA) because I just found it ad-hoc and can't really be tested 🤷‍♂ 
No screenshots since its not a visual change 🙂
> refactor: consolidated various generic error titles to one const (NOJIRA)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixed:
Data visualizer supports selection of orgunit levels/groups even if no parent/boundary orgunits are selected. However, the chart title does not seem to support this as it displays "in" both with and without parent orgunits. [DHIS2-8473](https://jira.dhis2.org/browse/DHIS2-8473)
Fixed by upgrading to [Analytics v4.3.24](https://github.com/dhis2/analytics/pull/372)
Example with parent orgunit: "District levels in Sierra Leone"
Without parent orgunit it says: "District levels in"
After fix:
> fix: upgrade analytics for chart title fix [DHIS2-8473]

- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/modules/currentAnalyticalObject.js
Fixes https://jira.dhis2.org/browse/DHIS2-8577
Maps app requires the `dataItemType` information for dimension items for correctly setting up the item type in the edit thematical layer dialog when switching from DV with a given AO
See screenshot from Maps app here:
> fix: pass dimensionItemType in current AO (DHIS2-8577)

- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/lineConfig.js
While working on the documentation for DV, I noticed "broken" options in the Axes tab for `Line` and `Area` vis types.
Before:
After:
> fix: fix axes options for line and area vis types

- packages/app/src/components/VisualizationOptions/Options/LegendDisplayStrategy.js
Tiny text change to make a legend option suit all vis types (not just "table"). Verified by @cooper-joe 
Before
After
> fix: legend option text to suit all vis types

- packages/app/src/components/Layout/Tooltip.js
Fixes [8753](https://jira.dhis2.org/browse/DHIS2-8753) (_No tooltip displayed when items exceed window length_), by reducing the max amount of items displayed in a tooltip to 5 and adding a `and X others...` message to replace the subsequent items.
1-5 items display as normal
6 items display` and X other...`
6+ items display `and X others...`
Note: shouldn't affect other tooltips, like the SV one which has its own logic. Same for no items.
----------------
**Examples**
50 items: `and 45 others...`
6 items: `and 1 other...`
5 items: just displays as normal
Single value vis type: unaffected
No items: unaffected
> fix: display 'and x others...' on tooltip (DHIS2-8753)

- packages/app/package.json
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/Tooltip.js
- packages/app/src/components/Layout/TooltipContent.js
- packages/app/src/components/Layout/__tests__/TooltipContent.spec.js
- yarn.lock
Fixes: https://jira.dhis2.org/browse/TECH-322
Part of the effort for reducing the technical debt in DV.
Rewrite the Chip and TooltipContent (renamed from Tooltip to solve name clashing issues with ui-core/Tooltip) components to use ui-core in place of material UI.
The ui-core Tooltip available positioning under the element is centered under it, not in the left corner.
A small issue is present when the Chip is dragged, and that is the Tooltip remains on the screen for the close timeout time.
I don't think there is a way to avoid this in the app.
What we might want is that as soon as the drag starts, the Tooltip is removed.
Screenshots
Before:
After:
> refactor: rewrite Chip and TooltipContent components (TECH-322)

- packages/app/i18n/en.pot
- packages/app/src/components/Layout/Tooltip.js
[DHIS2-8753](https://jira.dhis2.org/browse/DHIS2-8753) fix for v34. Backported https://github.com/dhis2/data-visualizer-app/pull/925 by cherry-picking https://github.com/dhis2/data-visualizer-app/commit/adaa4854fc00f76f0d413cab186b865293ebb6e2 and generating a new pot file. Please see the original PR for details.
> fix: display 'and x others...' on tooltip (DHIS2-8753) v34 backport 

- packages/app/i18n/en.pot
- packages/app/src/components/Layout/Tooltip.js
[DHIS2-8753](https://jira.dhis2.org/browse/DHIS2-8753) fix for v33. Backported https://github.com/dhis2/data-visualizer-app/pull/925 by manually copy-pasting the fix from https://github.com/dhis2/data-visualizer-app/commit/adaa4854fc00f76f0d413cab186b865293ebb6e2 and generating a new pot file. A clean cherry-pick wasn't possible since v33 didn't implement the `renderItems` method. Please see the original PR for details.
> fix: display 'and x others...' on tooltip (DHIS2-8753) v33 backport 

- package.json
- packages/app/package.json
- packages/app/src/components/DimensionsPanel/DndDimensionsPanel.js
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-8790](https://jira.dhis2.org/browse/DHIS2-8790).
Adds the browser default 'x' by passing through the `type` prop (which can be set to `search` to get the 'x'.
Depends on: https://github.com/dhis2/analytics/pull/408
> fix: dimension panel search field is missing the 'x' to clear (DHIS2-8790)

- packages/plugin/package.json
- yarn.lock
Use tilde rather than hat version because v33 needs to stay on 2.4.x of analytics
> chore: upgrade analytics and use tilde version for deduping in apps [v33]

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Part of fix for: https://jira.dhis2.org/browse/DHIS2-8638
Note: I already published data-visualizer-plugin v33.1.12 so dashboards could get it.
Finally, fully translated:
> fix: latest analytics library for period selector translations (v33)

- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/plugin/package.json
- yarn.lock
Implements the [latest Analytics changes](https://github.com/dhis2/analytics/pull/452/) for [DHIS2-8807](https://jira.dhis2.org/browse/DHIS2-8807).
- Bumps the Analytics version to [v.6.0.0](https://github.com/dhis2/analytics/releases/tag/v6.0.0)
- Removes `onDeselect` and `onReorder` from the props passed to `PeriodDimension`
Please see the Analytics change for full details and spec.
-------------
> feat: implement latest Period Selector from Analytics (DHIS2-8807)

- packages/plugin/package.json
- yarn.lock
BREAKING CHANGE: 
1. Marked as a breaking change because we need to move to version 35 to follow the convention of major version matching DHIS2 version
2. removed d2-analysis from plugin dependencies since it is not in use
3. yarn-deduplicate
> fix: yarn-deduplicate and remove unused d2-analysis

- packages/app/src/modules/__tests__/yearOverYear.spec.js
- packages/app/src/modules/yearOverYear.js
- yarn.lock
This bug is only on master and has not yet been released to play servers. So no Jira issue.
It was caused by decrementing the year after the function that gets the name, but before the function that gets the id.
P.S. A little yarn cleanup seems to have snuck into this PR when I ran a clean install.
Broken:
Fixed:
> fix: yoy chart mismatch between layout years, and chart years

- packages/app/src/components/VisualizationOptions/Options/ApprovalLevel.js
- packages/app/src/components/VisualizationOptions/Options/LegendSet.js
The query parameter value must be a string.
Support for booleans is eventually going to be added to DataEngine.
See: https://github.com/dhis2/app-runtime/issues/578.
> fix: fix paging query parameter passed to data engine

- .github/workflows/dhis2-artifacts.yml
Sets `cwd` to point at the monorepo app package.
> chore: set cwd to find the build folder

- .github/workflows/dhis2-artifacts.yml
Sets `cwd` to point at the monorepo app package.
> chore: set cwd to find the build folder (34.x)

- packages/plugin/src/ChartPlugin.js
Make sure `renderVisualization` is not run twice on mount.
> fix: avoid unnecessary plugin call (TECH-412)

- packages/app/i18n/en.pot
- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/lineConfig.js
- packages/app/src/modules/options/stackedColumnConfig.js
Fixes [DHIS2-9004](https://jira.dhis2.org/browse/DHIS2-9004)
Available options vary between vis types based on different configs ([spec](https://docs.google.com/spreadsheets/d/1XJxLoC7IAT5S3Pi7cUkKZoAAm4Rztx9aVNkiqGfirnU/edit#gid=0)), however the order of these options should be kept consistent to make it easy to find a certain option, regardless of which vis type is used. Using the `columnConfig` as a template, the other configs are now organised in a similar pattern.
- Removes two incorrect fields in `Style` tab and adds missing section titles (`areaConfig`, `lineConfig`), as per [DHIS2-9004](https://jira.dhis2.org/browse/DHIS2-9004)
- Moves `ShowData` from `Data` to `Style` (`areaConfig`, `lineConfig`, `stackedColumnConfig`)
- Adds missing section splitting in the `Data` tab …
> fix: reorder options for consistency (DHIS2-9004)

- packages/app/src/components/VisualizationTypeSelector/styles/VisualizationTypeSelector.module.css
Fixes [DHIS2-8643](https://jira.dhis2.org/browse/DHIS2-8643)
The visualization type selector (aka VTS, the menu accessed by the button in the top left corner) used to be hidden behind the visualization loading spinner because of an incorrect z-index. The VTS z-index has been bumped to 110 (loading spinner backdrop is set to 100) to prevent this from happening.
> fix: set visualization type selector z-index (DHIS2-8643)

- packages/app/src/components/Layout/Chip.js
The tooltip is now only surrounding the dimension icon and label, so the
3-dotted menu is not interfering with the click/timeout handling of the
tooltip.
Fixes: https://jira.dhis2.org/browse/DHIS2-9063.
Fixed version:
> fix: fix stuck tooltips in dimension chips DHIS2-9063

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/ColorSet.js
- packages/app/src/components/VisualizationOptions/Options/RadioBaseOption.js
- packages/app/src/modules/options.js
- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/barConfig.js
- packages/app/src/modules/options/columnConfig.js
- packages/app/src/modules/options/lineConfig.js
- packages/app/src/modules/options/pieConfig.js
- packages/app/src/modules/options/sections/colorSet.js
- packages/app/src/modules/options/stackedColumnConfig.js
- packages/app/src/modules/options/yearOverYearConfig.js
- packages/plugin/package.json
- yarn.lock
Part of the implementation for https://jira.dhis2.org/browse/DHIS2-670
Requires https://github.com/dhis2/analytics/pull/531
The PR adds a new option for `colorSet`.
It renders a radio selector with a list of available color sets (see screenshot).
Screenshots
The option is disabled when multiple axes are used
Things to complete:
* ~preview for the Mono patterns~: done using the patterns from Highcharts directly
> feat: implement colorSet option (DHIS2-670)

- packages/app/package.json
- packages/app/src/modules/__tests__/layout.spec.js
- packages/app/src/modules/__tests__/layoutAdapters.spec.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/plugin/package.json
- yarn.lock
Fixes https://jira.dhis2.org/browse/DHIS2-7876.
Most of the inplementation is in the analytics dependency, see: https://github.com/dhis2/analytics/pull/508.
The DV app needs to correctly configure the `ui.layout`object when loading an AO saved with 2 categories, otherwise the default layout adapter moves all dimensions besides the first from `rows` to `filters`.
> feat: support for two category charts [DHIS2-7876]

- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/config.js
- packages/app/src/modules/options/radarConfig.js
- packages/app/src/modules/options/stackedAreaConfig.js
- packages/plugin/src/modules/options.js
Fixes [DHIS2-9011](https://jira.dhis2.org/browse/DHIS2-9011).
Requires [@dhis2/analytics PR 550](https://github.com/dhis2/analytics/pull/550).
Specifically:
- remove the "Stacked values add up to 100%" option for Area
- add the same option to Stacked area
- enable multi axis in Series for Area
- disable multi axis in Series for Stacked area and Radar
> fix: option configs for various vis types

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/CheckboxBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/HideLegend.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1152 to 34.x
* Changes the title of the hideLegend option to a positive case (show).
* As the backend option is a negative case (hide), CheckboxBaseOption now has an inverted prop to flip the checked state.
> fix: rename and invert the hide legend option (#1152) (DHIS2-9003) v34

- packages/app/src/components/VisualizationOptions/Options/TextBaseOption.js
Manual backport of [DHIS2-9194](https://jira.dhis2.org/browse/DHIS2-9194) to v33
The 34 and 35 solution couldn't be cherry-picked as it contained changes not compatible for 33.
However the fix for this issue is simply passing the steps value as a number instead of a string. As mentioned by @janhenrikoverland  here: [comment](https://jira.dhis2.org/browse/DHIS2-9194?focusedCommentId=34665&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34665)
> fix: pass y-axis steps as number (DHIS2-9194) v33

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/PositiveNumberBaseType.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisDecimals.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisSteps.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1161 for v34
Had to change `ui` to `ui-core`, since v34 is using an older version of this library.
* New base type PositiveNumberBaseType added that only allows positive whole numbers
* Math.round prevents decimal numbers and returns Number instead of String, which fixes DHIS2-9194
* parseInt(value, 10) to allow for clearing the value with backspace
* Applies to both typing manually and by using the browser's built-in "stepper arrows".
* New help text for Steps, as per Slack discussion, Number of axis tick steps, including the min and max. A value of 2 or lower will be ignored.
> fix: Decimals and Steps options only allow positive values (DHIS2-9002, DHIS2-9194) (#1161) v34

- packages/app/i18n/en.pot
- packages/app/src/modules/options/areaConfig.js
- packages/app/src/modules/options/lineConfig.js
- packages/app/src/modules/options/stackedColumnConfig.js
Backport https://github.com/dhis2/data-visualizer-app/pull/1153 for v34
Regenerated the pot file in a separate commit.
* Removes two incorrect fields in Style tab and adds missing section titles (areaConfig, lineConfig), as per DHIS2-9004
* Moves ShowData from Data to Style (areaConfig, lineConfig, stackedColumnConfig)
* Adds missing section splitting in the Data tab (areaConfig, lineConfig)
* Changes the label const to instead use the getLabel function (areaConfig, lineConfig)
> fix: reorder options for consistency (DHIS2-9004) (519b0ba) v34

- yarn.lock
Just noticed a duplicate version of lodash in my previous branch, but I forgot to include it in the PR. To compensate I ran a full deduplication job across all deps instead  (`npx yarn-deduplicate yarn.lock`).
> chore: deduplicate yarn.lock

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/AggregationType.js
Backports https://github.com/dhis2/data-visualizer-app/pull/1151 to v34
Changes the help text for the aggregation type option.
> fix: change help text for aggregation type (#1151) (DHIS2-9000) v34

- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/DownloadMenu/styles/DownloadMenu.module.css
A double bottom border was showing in the sub-levels of the Download menu.
Fixed by properly using the `@dhis2/ui` components.
The sub-levels look a bit different than before, but now the correct ui components are used instead of divs with custom styling.
Before:
After:
There is a small issue with a double bottom border on the main menu which happens when using `FlyOut` within a `Popover` component. @dhis2/team-apps has been notified.
This issue will be likely fixed in a later patch.
> fix: fix double bottom border in Download menu

- packages/app/src/modules/layoutValidation.js
Depends on https://github.com/dhis2/analytics/pull/574 for the feature to work, but can safely be merged without it.
Removes the `dx` requirement for YOY types. If no DEGS or `dx` the server returns a `E7102` which is already handled by DV.
> feat: allow YOY without dx (DHIS2-8806)

- packages/app/package.json
- packages/app/src/modules/options/singleValueConfig.js
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-9340](https://jira.dhis2.org/browse/DHIS2-9340).
Depends on https://github.com/dhis2/analytics/pull/571.
This allows to format the numeric value in SV with a thousands separator.
It uses the same functions PT uses and looks at the `skipRounding` and `digitGroupSeparator` options, now available in the `Data` and `Style` option tabs.
Options:
Here's an example of a value with comma as digit group separator:
> fix: enable skipRounding and digitGroupSeparator options for SV (DHIS2-9340)

- packages/app/package.json
- packages/app/src/modules/current.js
- packages/app/src/reducers/__tests__/current.spec.js
- packages/plugin/package.json
- yarn.lock
Depends on https://github.com/dhis2/analytics/pull/574
Fixes [DHIS2-8808](https://jira.dhis2.org/browse/DHIS2-8808)
The `dx` dimension is now always `filter`, both in the app and the backend. The restriction where only the first item was picked has been removed.
> feat: move dx to filter for YOY which allows for multiple dx items (DHIS2-8808)

- packages/app/i18n/en.pot
- packages/app/src/actions/index.js
Fixes [DHIS2-9360](https://jira.dhis2.org/browse/DHIS2-9360)
If no name is provided in the Save dialog the save process will now default to a date-based name in the format of `Untitled {{visualizationType}} visualization, {{date}}`.
The date in turn is based on a localized version of `dd mmm yyyy`.
> fix: set a default name if saved vis is untitled (DHIS2-9360)

- packages/app/src/components/VisualizationOptions/Options/DigitGroupSeparator.js
- packages/app/src/components/VisualizationOptions/Options/SelectBaseOption.js
- packages/app/src/modules/options.js
- packages/app/src/reducers/settings.js
Fixes [DHIS2-9328](https://jira.dhis2.org/browse/DHIS2-9328) for DV.
The solution here works for the `digitGroupSeparator` option in DV, which is enabled for Single Value and Pivot Table visualization types.
A default value override from a select based connected component only works if the option is non toggleable.
Setting options defaults from system settings wasn't covered before; the whole DV options system needs to be revisited for better accommodate this requirement and other recent modifications.
The digit group separator can be set in the system settings app:
And it should be pre-selected in DV option's Style tab for new visualizations:
And it should be respected when displaying a numeric value:
> fix: digit group separator default from system settings (DHIS2-6328)

- packages/app/i18n/en.pot
- packages/app/src/components/MenuBar/MenuBar.js
- packages/app/src/modules/__tests__/error.spec.js
- packages/app/src/modules/error.js
Fixes [DHIS2-9310](https://jira.dhis2.org/browse/DHIS2-9310)
- Refactors the `parseError` to become a more generic function `getErrorVariantByStatusCode` instead
- Catches the new error code `E4030` and sets a custom message that replaces the default (server-side) message.
- Updates the tests to work accordingly.
> fix: Custom error message for deleting an AO used in Dashboards (DHIS2-9310)

- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/components/VisualizationOptions/Options/DigitGroupSeparator.js
- packages/app/src/components/VisualizationOptions/Options/SelectBaseOption.js
- packages/app/src/modules/options.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
Related to [DHIS2-9328](https://jira.dhis2.org/browse/DHIS2-9328).
This fixes the issue of the DGS default from system settings not being used when resetting the ui portion of the DV's Redux store, which ultimately caused the visualization (SV, PT) to not render the digit group separator correctly when working on a non-saved visualization.
The DGS in the store's ui was only set when the option in the options dialog was rendered/interacted with, so for a new visualization, the DGS was undefined even if it was set to a specific value in system settings.
> fix: DGS default from settings (DHIS2-9328)

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/PositiveNumberBaseType.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisDecimals.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisSteps.js
- packages/app/src/components/VisualizationOptions/__tests__/RangeAxisSteps.spec.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1161 for v33
Based on cherry-picking https://github.com/dhis2/data-visualizer-app/commit/b0996072769123a02249c63cb41cf347d90ad2f2
Not a clean CP, had to change quite a lot to adapt it to v33, since it uses MUI instead of ui/ui-core.
---------
---------
Original description:
* New base type PositiveNumberBaseType added that only allows positive whole numbers
* Math.round prevents decimal numbers and returns Number instead of String, which fixes DHIS2-9194
* parseInt(value, 10) to allow for clearing the value with backspace
* Applies to both typing manually and by using the browser's built-in "stepper arrows".
* New help text for Steps, as per Slack discussion, Number of axis tick steps, including the min and max. A value of 2 or …
> fix: Decimals and Steps options only allow positive values (DHIS2-9002, DHIS2-9194) (#1161) v33

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/PositiveNumberBaseType.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisDecimals.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisSteps.js
- packages/app/src/components/VisualizationOptions/__tests__/RangeAxisSteps.spec.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1161 for v33
Clean cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/1254/commits/972a175d85c946cda5161152a7f988c3ac389e5a
* New base type PositiveNumberBaseType added that only allows positive whole numbers
* Math.round prevents decimal numbers and returns Number instead of String, which fixes DHIS2-9194
* parseInt(value, 10) to allow for clearing the value with backspace
* Applies to both typing manually and by using the browser's built-in "stepper arrows".
* New help text for Steps, as per Slack discussion, Number of axis tick steps, including the min and max. A value of 2 or lower will be ignored.
> fix: Decimals and Steps options only allow positive values (DHIS2-9002, DHIS2-9194) (#1161) v32

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/CheckboxBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/HideLegend.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1152 to 33.x
Clean cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/1256/commits/3f26d3d740410962beca2a223a47ff8a59c31c38
* Changes the title of the hideLegend option to a positive case (show).
* As the backend option is a negative case (hide), CheckboxBaseOption now has an inverted prop to flip the checked state.
> fix: rename and invert the hide legend option (#1152) (DHIS2-9003) v32

- packages/app/package.json
- packages/app/src/components/VisualizationOptions/styles/TextStyle.module.css
- packages/plugin/package.json
- yarn.lock
Issue: In the options modal, using a short Chrome browser window, when the color picker was opened for an element below-the-fold, the modal jumps up to fit the color picker.
Solution: This is caused by using `position: absolute` as part of the custom color picker. Solved by wrapping the container of that element with `position: relative`.
-----------------
Bug: Before jumping
Bug: After jumping
Fix: Not jumping
> fix: modal is bumped up when the color picker is opened

- packages/app/src/components/Layout/DefaultLayout/DefaultLayout.js
- packages/app/src/components/Layout/PieLayout/PieLayout.js
- packages/app/src/components/Layout/PieLayout/styles/PieLayout.style.js
Vis types `pie` and `gauge` support only a single dimension, all other dimensions are filters. Thus is makes sense to allocate less space (30%) for the series dimension and more space (70%) for filters.
> fix: pie layout axis width

- packages/app/src/actions/index.js
Manual backport of https://github.com/dhis2/data-visualizer-app/pull/1273/commits/aca9a9c783cd978ed2363b7172b678ddb4d9c0a4 for [DHIS2-9360](https://jira.dhis2.org/browse/DHIS2-9360)
Saving named visualization again now retains it's name properly. As seen in https://github.com/dhis2/data-visualizer-app/pull/1273
> fix: set a default name if saved vis is untitled (DHIS2-9360) v34

- packages/app/src/components/App.js
- packages/app/src/components/MenuBar/MenuBar.js
The app should reset also when the URL does not change, like when a
non-saved visualization is shown and New in the FileMenu is clicked.
This used to work in 2.34.
(cherry picked from commit 0dc16ed35c83cd4f558e982eb61bf10c67741127)
See the original PR #1406 for more information.
> fix: reset app when New is clicked (v35) (DHIS2-9876)

- cypress/elements/common.js
- cypress/integration/confirmLeave.cy.js
- cypress/integration/open.cy.js
- cypress/integration/save.cy.js
1. fix flaky test
2. add a common way to change an AO
---
`confirmLeave` is flaky, I think this is caused by the way MUI handles updates in the data dimension selector (soon to be replaced by non-MUI). The test replaces data items which sometimes isn't performed in order, even though a `then` is used. This PR changes the test to replace period items instead, since the new period selector (non-MUI) seems to be stable. 
`replacePeriodItems` was added to create a common way to change an AO that's easy to use. Period, Data and Org units are the only dimensions that can be assumed are in all AOs, so when loading a "random" AO that should be changed, it must change one of these three dimensions. However Data is flaky (issue above) and the org unit tree is quite complex (plus it might suffer …
> test: replace period instead of data in confirmLeave to avoid flakiness

- packages/app/src/reducers/ui.js
Implements [DHIS2-10007](https://jira.dhis2.org/browse/DHIS2-10007)
---
Changes the order of item attributes when adding, to prevent the attributes from switching place. 
Previously having `1` and adding `2` would result in `[2, 1]`, but this has now been fixed to return `[1, 2]` instead.
> fix: change order of item attr when added (DHIS2-10007)

- packages/plugin/src/api/legendSets.js
[No JIRA] - extends https://github.com/dhis2/data-visualizer-app/pull/1369
1. Add missing name for legend sets
---
https://github.com/dhis2/data-visualizer-app/pull/1369 introduced a change to the fetching of legend sets from the API which removed the name for the legend sets themselves. This PR adds back the missing name.
---
_before this fix, legend set name missing_
_with this fix, legend set name working again_
> fix: add missing name for legend sets

- cypress/elements/common.js
- cypress/integration/save.cy.js
- cypress/integration/visTypes/scatter.cy.js
1. Reenable delete tests
2. Change period test data
---
1. The delete tests were skipped because of the backend bug [DHIS2-10140](https://jira.dhis2.org/browse/DHIS2-10140), which has now been fixed. The tests have thus been reenabled again.
2. Some tests were failing because they were expecting a visualization to be shown when instead the "No data" warning message was displayed on screen. The period test data was using quarterly data, but as its now Q1 2021, which happens to not have any test data in the DB, it's safer to use `Quarters this year` which is more likely to have test data and not end up showing the warning.
> test: reenable delete tests and change period test data

- cypress/integration/confirmLeave.cy.js
- cypress/integration/save.cy.js
1. `confirmLeave` should check visualization instead of chart title
2. `start` should wait for AO to be loaded when opening
1. `confirmLeave` was checking the chart title (highcharts), but as its opening a random visualization, which could be a non-highcharts type (SV and PT), it was failing some times when it couldn't find the highcharts title. It now checks the visualization in general instead (which takes this in to account already).
2. `start` was opening an AO but didn't wait for it to load, causing it to sometimes be flakey depending on the output of the race condition.
> test: save and confirm leave flakey

- packages/app/package.json
- packages/app/src/api/analytics.js
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/plugin/package.json
- yarn.lock
See https://github.com/dhis2/analytics/pull/776.
Also, pass baseUrl from the useConfig hook instead of relying on d2.
The downloadImage still uses d2 as there isn't support for this type of
POST request yet, although there is an open PR
(https://github.com/dhis2/app-runtime/pull/753).
Fixes [DHIS2-9789](https://jira.dhis2.org/browse/DHIS2-9789)
**Requires https://github.com/dhis2/analytics/pull/776**
**Requires https://github.com/dhis2/analytics/pull/785**
---
1. Fix download links for dataValueSet.
---
The actual fix is in the analytics library.
---
-   [ ] the download for image/pdf still uses `d2` because dataEngine does not support POST requests passing a custom Content-type header. Also, I'm not sure how to handle the response to get the blob used to build the download URL in the …
> fix: use the download links for dataValueSet via analytics DHIS2-9789

- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/MenuButton/styles/MenuButton.module.css
1. remove the bottom double border
2. use icons from `ui`
3. enable the Escape key for closing the menu
---
Solved the double bottom border issue in the menu, due to wrong use of `ui` components.
The Escape key closes the menu, this functionality was lost after replacing MUI with `ui`.
---
> fix: download menu - double border, ui icons, esc for closing

- cypress/elements/fileMenu/index.js
- cypress/elements/fileMenu/open.js
- cypress/elements/fileMenu/save.js
- cypress/integration/save.cy.js
- cypress/integration/start.cy.js
- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/MenuBar/MenuBar.js
- packages/app/src/modules/fields/baseFields.js
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-9821](https://jira.dhis2.org/browse/DHIS2-9821)
**Requires https://github.com/dhis2/analytics/pull/655**
**Requires https://github.com/dhis2/analytics/pull/798**
---
1. Replace `d2-ui-file-menu` with `FileMenu` component from `@dhis2/analytics`
---
There are no functional differences, only small style differences.
Refer to the analytics PR for more info and screenshot.
---
The use of Esc for closing the menu is not supported in `ui`.
Ideally we should keep the functionality, it would be helpful if it can be implemented in a centralized way, but given the open/close state is handled in the app via conditional rendering, I'm not sure how that can work.
See: https://github.com/dhis2/notes/discussions/215
**Solved** for now in the FileMenu itself.
> refactor: replace d2-ui-file-menu with analytics/FileMenu

- packages/app/src/components/Visualization/Visualization.js
Implements [DHIS2-10329](https://jira.dhis2.org/browse/DHIS2-10329)
---
1. fix regression where the custom error screens disappeared
---
The previous code expected the `errorCode` at the root level of the response object.
Now it is available under `details`.
---
Before:
After:
> fix: get the errorCode for the analytics response in the right place

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-10289](https://jira.dhis2.org/browse/DHIS2-10289)
---
Highcharts 9.0.0 fixes the missing pattern preview, analytics dep has it already, bump dep in app.
Before (regression):
After:
> chore: update @dhis2/analytics dep for getting latest Highcharts

- packages/plugin/src/__tests__/VisualizationPlugin.spec.js
- packages/plugin/src/__tests__/yoy-weekly-edge-cases.spec.js
- packages/plugin/src/api/analytics.js
- packages/plugin/src/modules/analytics.js
- packages/plugin/src/modules/fetchData.js
- yarn.lock
Fixes [DHIS2-9729](https://jira.dhis2.org/browse/DHIS2-9279)
**Requires https://github.com/dhis2/analytics/pull/758**
---
Reworked the way data series for YOY charts which uses relative week periods are generated.
To avoid the problems described in the JIRA ticket, where data points are not correctly aligned when comparing week ranges of different years, the logic is now based on a matrix of xAxis index and period ids, which is generated from the analytics responses in the DV plugin.
From the matrix a map object is computed, and used to get the correct xAxis position where to plot a value based on the period id.
This solves both the problem of week 53 that some years have, and the problem of different week ranges for different years when using a relativePeriodDate.
Requesting the last 4 …
> fix: YOY charts with relative week periods DHIS2-9729

- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/Layout/ChipMenu.js
Implements [DHIS2-10514](https://jira.dhis2.org/browse/DHIS2-10514)
---
1. removes double border in contextual menus
---
The double bottom border in menus is a known issue that happens when using a `FlyoutMenu` inside a `Popover` component.
The proper way to do it is wrapping a `Popper` in a `Layer` (needed for attaching the click outside the menu callback).\
The same approach is used for FileMenu and DownloadMenu.
---
Before:
After:
> fix: avoid double border in contextual menu DHIS2-10514

- packages/app/src/components/Visualization/Visualization.js
1. fix bug which caused dimension ids instead of names to be shown in the layout chip tooltips
---
See attached screenshots.
The bug only happens for saved visualizations when no data is returned.
Metadata is always present in the response, but when there is no data to show, the `EmptyResponseError` was thrown before storing the metadata for the dimension selection.
The fix makes sure the metadata in the Redux store is always updated, and any error is thrown afterwards.
Before:
After:
> fix: store metadata also when no data is returned

- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/app/src/components/Visualization/Visualization.js
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/modules/fetchData.js
- packages/plugin/src/modules/getRequestOptions.js
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/841**
---
1. Pass `nameProp` to `DynamicDimension`
2. Pass `displayProperty` to `/analytics`
---
_shortname now properly displayed for dynamic dimensions_ 
_shortname now properly displayed in places which rely on the metadata from /analytics_
> fix: use nameprop for dynamic dimensions and /analytics

- cypress/elements/common.js
- cypress/elements/dimensionModal/dataDimension.js
- cypress/elements/dimensionModal/index.js
- cypress/elements/dimensionModal/orgUnitDimension.js
- cypress/elements/dimensionsPanel.js
- cypress/elements/fileMenu/save.js
- cypress/elements/optionsModal/axes.js
- cypress/elements/optionsModal/fontStyles.js
- cypress/elements/optionsModal/index.js
- cypress/elements/optionsModal/lines.js
- cypress/elements/optionsModal/outliers.js
- cypress/elements/optionsModal/subtitle.js
- cypress/integration/options/axes.cy.js
- cypress/integration/options/fontStyles.cy.js
- cypress/integration/start.cy.js
- cypress/integration/visTypes/scatter.cy.js
- cypress/support/commands.js
- cypress/utils/config.js
- cypress/utils/random.js
- cypress/utils/window.js
- packages/app/src/components/VisualizationOptions/Options/AxisLabels.js
- packages/app/src/components/VisualizationOptions/Options/CheckboxBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/HideLegend.js
- yarn.lock
1. Improve / extend tests for font style options
2. Minor refactor of common functions to reduce duplication (`expectAppToNotBeLoading`, `clickCheckbox`, `typeInput`, `clearInput`)
3. Minor improvement of Scatter by selecting more org units
4. Comment out a test in start.cy.js caused by a known backend bug
---
Tip: The vast majority of the changes are in `fontStyles.cy.js`, however don't compare the change, just look at the new file as a whole, as it's been completely refactored and GH tries to "compare" it in a weird way which just adds confusion.
> test: font style testing

- packages/app/src/modules/fields/baseFields.js
1. Enable outlier options to be fetched when requesting an AO
---
_visualization has outliers when loaded_
_outlier options persisted after load_
> fix: include outlierAnalysis in AO request

- packages/app/src/components/Layout/ScatterLayout/ScatterAxis.js
1. Persist the order of the data items when swapping in scatter and changing vis type
---
_before, swapping item1-item2 to item2-item1 shows up as item1-item2 in a column chart_
https://user-images.githubusercontent.com/12590483/110327164-ea65a600-8019-11eb-80c9-3767deeac885.mov
_after, swapping item1-item2 to item2-item1 is persisted as item2-item1 in a column chart_
https://user-images.githubusercontent.com/12590483/110327186-f18cb400-8019-11eb-83c5-b7839c5781d4.mov
> fix: set vertical before horizontal when swapping

- packages/app/src/components/Layout/ScatterLayout/ScatterAxis.js
1. fix double border in layout chip for Scatter visualizations
---
Before:
After:
> fix: fix double border in chip menu for scatter

- packages/app/src/reducers/ui.js
- yarn.lock
1. Prevent ghost items from appearing when switching vis type
---
Previously items were never removed from `itemsByDimension` when adding vertical or horizontal items in scatter, so all items ever used would appear when changing vis type. This fix prevents deleted items from persisting beyond its lifespan. However, the order (vertical vs horizontal) isn't respected, so horizontal items might appear before vertical ones (depending on in which order they were added). This shouldn't be too critical though.
---
_with ghosts_
https://user-images.githubusercontent.com/12590483/110346473-e0e73880-802f-11eb-8c17-db863d74550a.mov
_without ghosts_
https://user-images.githubusercontent.com/12590483/110346508-eb093700-802f-11eb-8307-8493607426fc.mov
> fix: prevent ghost items in itemsByDimension

- packages/app/package.json
- yarn.lock
Fixes [DHIS2-10625](https://jira.dhis2.org/browse/DHIS2-10625)
---
1. use patched d2-ui-interpretations dep
---
The actual fix is in d2-ui-interpretation and d2
When opening the interpretations panel no requests to `userGroups` are made anymore:
> chore: bump d2 and d2-ui-interpretations deps

- packages/app/src/actions/settings.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/reducers/__tests__/settings.spec.js
- packages/app/src/reducers/settings.js
- packages/plugin/src/ChartPlugin.js
1. avoid visualization plugin double render
---
The cause for it was the `userSettings` prop passed to `VisualizationPlugin`. The prop was a new object every time, causing unwanted re-render.
The fix prevents the Highcharts config generation to run multiple times.
> fix: avoid visualization plugin double render

- packages/plugin/src/ChartPlugin.js
1. Visualizations in dashboard were not rerendering to fit the item size in the following situations:
* item fullscreen
* edit item resize
* change screen width (e.g., switch to/from small screen)
---
Dashboard and Data Visualizer apps have different approaches regarding visualization size and resizing. DV vis containers have display flex and use a counter that updates when the window is resized, to trigger a re-render of the visualization. In Dashboard, the container has a set width and height, which change on any of the above resizing scenarios. It does not use a counter.
The new effect will end up being specific to dashboard, while the existing effect that responds to `renderCounter` will be specific to DV. A future improvement would possibly be to use the same mechanisms for both …
> fix: detect style changes from dashboard for re-rendering visualization

- packages/plugin/src/ChartPlugin.js
1. Fix double rendering in DV after the window is resized
---
The check on `renderCounter` value different than `null` is not working after the window is resized.
The next time the check is performed, `renderCounter` maintained the value assigned and triggers a rerender because is always going to be different than `null`.
The fix is then to compare with the previous version.
> fix: avoid re-render after 1st resize

- yarn.lock
Backports [DHIS2-9829](https://jira.dhis2.org/browse/DHIS2-9829) to v34
**Requires https://github.com/dhis2/analytics/pull/876**
> fix: render trendlines in front of columns (DHIS2-9829) v34

- packages/app/package.json
- yarn.lock
Fixes [DHIS2-9789](https://jira.dhis2.org/browse/DHIS2-9789)
"Backport" via `d2` which is used here for the analytics requests.
> fix: fix download links for dataValueSet DHIS2-9789 v35

- packages/app/package.json
- packages/app/src/assets/ArrowDown.js
- packages/app/src/components/Interpretations/InterpretationsButton.js
- packages/app/src/components/Interpretations/__tests__/IterpretationsButton.spec.js
- packages/app/src/components/Interpretations/styles/InterpretationsButton.module.css
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/TooltipContent.js
- packages/app/src/components/Layout/styles/Chip.style.js
- packages/app/src/components/Layout/styles/Tooltip.style.js
- packages/app/src/components/VisualizationOptions/VisualizationOptionsManager.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/components/VisualizationTypeSelector/styles/VisualizationTypeSelector.module.css
- packages/plugin/package.json
- yarn.lock
1. Remove the last of MUI icons and replace them with `ui` icons
---
DV still used some icons from MUI.
Now the `ui-icons` are available there is no reason to keep MUI icons and the extra dependency.
Discussed with @cooper-joe  some of the replacements and got approval, it would be good anyway if @cooper-joe can have a look to make sure all is good.
---
-   the `FatalErrorBoundary` component is using an large icon, the PR replaces it with the equivalent icon from `ui-icons` but the size is not the same.
The component is not in use at the moment, and most probably it's going to be revisited in a separate PR.
**Update**: the component wasn't in use because is now part of the app shell, it has been removed from DV.
- some icons are imported from `@dhis2/analytics` there will be another PR …
> refactor: remove MUI icons

- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/components/Visualization/__tests__/utils.spec.js
- packages/app/src/components/Visualization/utils.js
The "most viewed" section works by first fetching the "favourites" and then fetching the types of each item.
If, for whatever reason, there's a mismatch between these two results (i.e. not all favourites have a corresponding item in the type response) the app crashes.
This change prevents this from happening by excluding the mismatched items.
Will lead to favourites being missing from the list (maybe not ideal) but at least the app won't crash.
---
_no visual changes_
> fix: start screen vis type crash

- packages/app/src/api/mostViewedVisualizations.js
- packages/app/src/components/Visualization/StartScreen.js
Implements [DHIS2-11065](https://jira.dhis2.org/browse/DHIS2-11065)
---
1. pass username to the favorites endpoint to get a user specific result
---
_the start page now shows the most viewed visualizations specific for the user_
> fix: pass username to the favorites endpoint (DHIS2-11065)

- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/__tests__/VisualizationPlugin.spec.js
1. properly await `ouLevels` to prevent race condition
---
There's an issue on dashboards where dashboard items fail to load.
It's caused by [ouLevelUtils in Analytics](https://github.com/dhis2/analytics/blob/37b3c6650924ee92c948dd5eeaee12a03b1be159/src/modules/ouLevelUtils/index.js#L19) receiving undefined `ouLevels`, which are provided by https://github.com/dhis2/data-visualizer-app/blob/06f0426626d47c0f181cbf261ed6fc73c400a96a/packages/plugin/src/VisualizationPlugin.js#L92
As the `ouLevels` are fetched in a `useEffect`, there's a race condition where the fetching sometimes doesn't finish before the component returns. This is prevented by only returning if `ouLevels` are finished fetching.
---
_error in dashboards_
> fix: await ou levels

- packages/plugin/src/ChartPlugin.js
- packages/plugin/src/ContextualMenu.js
- packages/plugin/src/VisualizationPlugin.js
Implements [DHIS2-11061](https://jira.dhis2.org/browse/DHIS2-11061)
**Requires https://github.com/dhis2/analytics/pull/918**
---
1. Add drill down to column and bar vis types
---
Adds a drill down menu (same as for pivot tables) to column, bar, stacked column and stacked bar. 
Most of the change is in Analytics. DV just changes `onToggleContextualMenu` a bit to fit the new vis types and passes that prop to the `createVisualization` function. 
The menu itself is unchanged and thus works exactly like it does for pivot tables.
Note that org unit has to be in either series or category for the menu to appear on click.
`onToggleContextualMenu` now receives the ref directly, instead of having it wrapped in a `current` prop. The `data` prop has the same structure as before, but Analytics only …
> feat: drill down org units in bar and column charts (DHIS2-11061)

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/ContextualMenu.js
- packages/plugin/src/VisualizationPlugin.js
- yarn.lock
Implements a fix for [DHIS2-11061](https://jira.dhis2.org/browse/DHIS2-11061)
**Requires https://github.com/dhis2/analytics/pull/931**
---
1. Change the popup placement to `right-start`
2. Hide drill down from dual category when org unit is used as the first category
3. Prevent the popup from opening empty while its still loading.
---
1. Position `right` didn't work for tall items (columns), as it would put the popup in the vertical center. With `right-start` it goes to the top of the right side.
2. Drill down for dual category when the org unit is the first category doesn't make sense, as the column clicked doesn't represent an org unit. To prevent this, dual category drill down is only available when the column is an org unit (i.e. org unit is the second category)
3. Previously the …
> fix: drill down bugs (DHIS2-11061)

- packages/app/src/components/AxesTabs/styles/AxesTabs.module.css
- packages/app/src/components/VerticalTabBar/styles/VerticalTabBar.module.css
- packages/app/src/components/VisualizationOptions/Options/AxisTitle.js
Implements fixes for [DHIS2-10902](https://jira.dhis2.org/browse/DHIS2-10902)
---
1. Clear title text when option `None` is selected
2. Prevent elements from overlapping on a small screen
---
_before_
_after_
> fix: axis title bugs (DHIS2-10902)

- packages/plugin/src/VisualizationPlugin.js
Implements a bug fix for [DHIS2-11061](https://jira.dhis2.org/browse/DHIS2-11061)
Reorder the contextual menu props to make sure the ref (which controls the rendering) is only called once the config (content) is set.
Prevents `ContextualMenu` from rendering twice when used in the chart plugin.
> fix: drill down bug fix (DHIS2-11061)

- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/components/Visualization/styles/StartScreen.module.css
Implements [DHIS2-11352](https://jira.dhis2.org/browse/DHIS2-11352) for v36
---
1. Wraps the icon for Scatter
---
_before_
_after_
> fix: missing scatter icon (DHIS2-11352) v36

- packages/app/package.json
- yarn.lock
1. bumps `d2-ui-interpretations` version
---
Avoids a crash when opening the interpretations panel with a locale with `language_country` format
See https://github.com/dhis2/d2-ui/pull/700
> fix: fix locale format passed to Intl in interpretations

- packages/app/package.json
- yarn.lock
1. bumps `d2-ui-interpretations` version
---
Avoids a crash when opening the interpretations panel with a locale with `language_country` format
See https://github.com/dhis2/d2-ui/pull/700
> fix: fix locale format passed to Intl in interpretations v35

- cypress/elements/optionsModal/index.js
- cypress/integration/options/legend.cy.js
- cypress/utils/window.js
- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- yarn.lock
Implements [DHIS2-11239](https://jira.dhis2.org/browse/DHIS2-11239)
**Requires https://github.com/dhis2/analytics/pull/982**
---
1. check vis type before displaying the legend key
2. add Cypress tests for options bleed
---
Legend set options were bleeding in to non-supported vis types, as only the existence of a legend set in itself was the criteria to apply legend specific options. Since the user can apply the legend for a supported type and switch to a non-supported type, the current vistype needs to be verified before applying the options.
> fix: legend options bleed (DHIS2-11239)

- packages/app/package.json
- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/components/App.js
- packages/app/src/components/__tests__/App.spec.js
- yarn.lock
Had to replace the old school `store.dispatch` in components, which is no longer available in the latest version of `react-redux`. 
The mock store in the tests still provide this so the tests are still using that, but we may want to review the jest tests and discard what we think isn't useful anymore, now that we have cypress.
> chore: upgrade react-redux to 7.2.4

- cypress/elements/optionsModal/index.js
- cypress/elements/optionsModal/legend.js
- cypress/elements/optionsModal/series.js
- cypress/integration/options/legend.cy.js
- cypress/utils/data.js
- cypress/utils/window.js
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/ColorSet.js
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- yarn.lock
Implements [DHIS2-11239](https://jira.dhis2.org/browse/DHIS2-11239)
**Requires https://github.com/dhis2/analytics/pull/983**
---
1. Correctly removes legend from column-as-line items 
2. Fixes a visual regression for the pattern preview due to a highcharts version bump
3. Implements the latest version of Analytics that also fixes:
- 3a. Prevent gauge from applying legend to fill when text is selected
- 3b. Add missing series key icon for trendline
- 3c. Add missing series key icon for pattern
---
_column-as-line won't display a legend_
_pattern and trendline icons in the series key display correctly_
_color set patterns_
> fix: legend key bugs (DHIS2-11239)

- packages/plugin/src/styles/VisualizationPlugin.style.js
Implements [DHIS2-11239](https://jira.dhis2.org/browse/DHIS2-11239)
---
1. Prevents the outline of the legend key button to be clipped at the top
---
Note the top part of the yellow outline in the screenshots below:
_before_
_after_
> fix: prevent outline clipping (DHIS2-11239)

- .github/workflows/dhis2-artifacts.yml
Fix failing dependabot PR checks (e.g. https://github.com/dhis2/data-visualizer-app/pull/1816/checks?check_run_id=3286817639) by preventing dependabot PRs from running the artifacts job. Reference: https://github.com/dhis2/workflows/blob/master/ci/dhis2-verify-app.yml#L115
> chore: prevent dependabot prs to run the artifacts job

- packages/app/src/components/VisualizationOptions/Options/AxisTitle.js
- packages/app/src/reducers/ui.js
Fixes [DHIS2-11650](https://jira.dhis2.org/browse/DHIS2-11650)
---
1. Prevent "NONE" from being stored / saved
---
Backend only supports saving "CUSTOM" and "AUTO", so the "NONE" option needs to be excluded from being stored and saved.
Setting the option to null when "NONE" is being used means that the store will strip out that value and thus strip out the whole axis options object, so setting "NONE" resets the store back to its original state as it should.
> fix: only store auto and custom title options (DHIS2-11650)

- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/Layout/ChipMenu.js
- packages/app/src/components/Layout/ScatterLayout/ScatterAxis.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/components/VisualizationTypeSelector/styles/VisualizationTypeSelector.module.css
- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/styles/VisualizationPlugin.module.css
- yarn.lock
This appends the manually created portals to the portal-root-node used by the dhis2-ui `Portal` component. As a result the layering issues are resolved.
While these changes fix the problem, they are not ideal because this requires intimate knowledge of the how the layering mechanism works in `dhis2/ui`. A more suitable long-term solution would be to switch from `createPortal` to using the `Portal` component from `@dhis2/ui`. However since that component is currently internal it is not a viable solution yet.
I will check with the UI team if we can start exposing the `Portal`.
> fix: append manually created portals to portal-root-node from app-shell

- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/Layout/ChipMenu.js
- packages/app/src/components/Layout/ScatterLayout/ScatterAxis.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/components/VisualizationTypeSelector/styles/VisualizationTypeSelector.module.css
- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/styles/VisualizationPlugin.module.css
- yarn.lock
* fix: append manually created portals to portal-root-node from app-shell
* refactor: use layer from ui
* style: reformat code
* fix(layer): do not override the default level
* refactor: remove unused backdrop styles
Co-authored-by: Viktor Varland <viktor@dhis2.org>
> fix: use layer component for backdrop and remove level overrides (#1859) (v37)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-11725](https://jira.dhis2.org/browse/DHIS2-11725)
**Requires https://github.com/dhis2/analytics/pull/1035**
---
1. Bump Analytics to latest
More info in the Analytics PR
> fix: bump analytics to latest (DHIS2-11725)

- packages/app/src/modules/fields/baseFields.js
- packages/plugin/src/modules/options.js
Part of the implementation for [DHIS2-11057](https://jira.dhis2.org/browse/DHIS2-11057)
---
1. Fetch the PT fix headers options on visualization load
---
The options can be saved, but need to be in the list of fields when fetching the visualization.
> fix: fetch PT fix headers options

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
1. Bump analytics to 20.4.6 with fixes to the PT fixed headers
> fix: bump analytics to latest

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
1. Bump analytics to 20.4.6 with fixes to PT fixes headers
> fix: bump analytics to latest v37

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/1048**
---
1. Update analytics with the fix for SV no data issue
---
The version bump here is needed for the plugin also used in dashboard app where the problem showed.
DV has a different handling for the no data situation, so no apparent changes in DV.
> fix: update analytics with SV no data fix

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport of https://github.com/dhis2/data-visualizer-app/pull/1892
**Requires https://github.com/dhis2/analytics/pull/1048**
---
1. Update analytics with the fix for SV no data issue
---
The version bump here is needed for the plugin also used in dashboard app where the problem showed.
DV has a different handling for the no data situation, so no apparent changes in DV.
> fix: update analytics with SV no data fix v37

- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
Implements [DHIS2-XXXX](https://jira.dhis2.org/browse/DHIS2-XXXX)
1. Bug fix
---
The `sGetDimensionItemsByAxis` incorrectly returned `undefined` if more than 1 dimension was selected on an axis.
The reason was that an array was passed to `sGetUiItemsByDimension` instead of a dimension id causing that function to return `undefined`.
The fix is looping through the dimensions array and call `sGetUiItemsByDimension` for each dimension before returning a flattened list of dimension items.
> fix: return a flat list of dimension items with multiple dimension on axis

- cypress/elements/dimensionModal/dataDimension.js
Seems there's an issue with Cypress using the outdated list of transfer items when the data type has changed in the data dimension modal, e.g. going from "all" to "indicators" would still try to select an item from the "all" list.
The `expectSourceToNotBeLoading` was added after the type has been switched to hopefully counter this.
> test: wait for loading to finish when data type has changed

- packages/app/src/components/VisualizationOptions/Options/ApprovalLevel.js
- packages/app/src/components/VisualizationOptions/Options/LegendSet.js
Implements [DHIS2-11913](https://jira.dhis2.org/browse/DHIS2-11913)
---
1. Fix crash when the query for fetching legend sets is run
---
This was already fixed in 2.35 and it's being solved at later in app-runtime, so now it's ok to pass a boolean to a query parameter.
34.x uses an old version of app-runtime which does not have support for boolean type query parameters.
See also #1083.
> fix: fix paging query parameter passed to dataQuery (DHIS2-11913)

- packages/app/src/modules/fields/nestedFields.js
Fixes [DHIS2-12264](https://jira.dhis2.org/browse/DHIS2-12264)
---
1. fix empty label for preselected legend set option
---
After the structure for the legend option changed to an object with keys and a nested object for legend set, the legend set label was not fetched from the api, causing an empty option in the dropdown (see screenshot).
The fix is about fetching only the fields needed for `legend` in the AO.
Before:
After:
> fix: make sure the legend set name is fetched DHIS2-12264

- cypress/elements/dimensionModal/orgUnitDimension.js
- cypress/integration/dimensions/orgUnit.cy.js
- cypress/integration/visTypes/scatter.cy.js
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adapts the Cypress tests to the changes introduced in the latest Analytics version, specifically that when `User org unit` is selected (which is the new default state when creating a new AO), `Level` and `Group` dropdowns are disabled. ([Analytics PR](https://github.com/dhis2/analytics/pull/1100)).
Before accessing the `Level` or `Group` dropdowns, the `User org unit` needs to be deselected so that they are enabled again (plus making sure that `Sierra Leone` is selected).
> test: selecting level / group with user org unit

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/CheckboxBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/FixColumnHeaders.js
- packages/app/src/components/VisualizationOptions/Options/FixRowHeaders.js
- packages/app/src/components/VisualizationOptions/VisualizationOptionsManager.js
- packages/app/src/components/VisualizationOptions/__tests__/CheckboxBaseOption.spec.js
- packages/app/src/modules/options/config.js
- packages/app/src/modules/options/pivotTableConfig.js
**Requires https://github.com/dhis2/analytics/pull/1057**
---
1. Add help text support to the `CheckboxBaseOption`
2. Add help text to both `FixRowHeaders` and `FixColumnHeaders` options depending on the layout selection
---
See the PR in analytics for more info about the missing borders issue with fixed headers.
The solution to that issue is in analytics, but in DV we needed a way to explain the user why the option does not appear to do anything even if it is enabled.
For that the `helpText` is used and the `CheckboxBaseOption` is now using ui's `CheckboxField` instead of `Checkbox`.
The 2 options for fix headers have a prop passed which tells if the corresponding axis in the layout has a selection (dimension items) or is empty (no dimension items selected), this is used to …
> fix: PT fixed headers help text

- packages/app/src/components/IconButton/IconButton.js
- packages/app/src/components/IconButton/styles/IconButton.module.css
- packages/app/src/components/Layout/ChipMenu.js
- packages/app/src/components/Layout/ScatterLayout/ScatterAxis.js
- packages/app/src/components/Layout/styles/Menu.style.js
No issue number available
---
1. Adds hover style to show-more button in the chip
2. I have removed quite a lot of code that seemed to be redundant
3. Aligns styling of Chip between ER and DV
---
I basically did exactly the same thing here as I did in https://github.com/dhis2/event-reports-app/pull/903. In ER this component was being used in one place only, but here in DV it was also being used by the `ScatterAxis`. But upon further inspection it turned out that the style object passed to the IconButton from the ChipMenu was actually undefined, and also the chips in the scatter axis didn't look quite right. So in the end I simply did exactly the same changes here as I did in ER and I think it looks correct.
---
Hover style:
> feat: add hover style to chip-menu-button

- packages/app/src/actions/index.js
- packages/app/src/components/Visualization/Visualization.js
Implements [DHIS2-12915](https://jira.dhis2.org/browse/DHIS2-12915)
---
1. Adapts the error message for E7124 to the specific dimension, either `dx`, `ou` or fallback to a generic server error
---
> fix: adapt error message to specific dimension (DHIS2-12915)

- packages/app/src/components/UserSettingsProvider.js
Implements [DHIS2-10174](https://jira.dhis2.org/browse/DHIS2-10174)
---
1. Solves the issue with `shortName` not being displayed even when that system/user setting is in use
---
The typo was first introduced by changing 
https://github.com/dhis2/data-visualizer-app/pull/1691/files#diff-88e65845537b664e65118a925f68f58981ff188e8b91d5e1d312cb040787f5c2L12
to
https://github.com/dhis2/data-visualizer-app/pull/1691/files#diff-8c7632f9344bbb0929aa941f9e9088c8a73bf0ef619c7757b707281520348399R27
---
-   [ ] Org unit tree still doesn't display the `shortName` properly. Libs ticket: https://dhis2.atlassian.net/browse/LIBS-314
---
> fix: correct typo with display name property (DHIS2-10174)

- packages/app/src/components/Visualization/Visualization.js
Implements [DHIS2-12915](https://jira.dhis2.org/browse/DHIS2-12915)
---
Partial cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/2009 (only the `Visualization.js` part, as 36.x doesn't have the `ALL_ITEMS` implementation anyway)
> fix: adapt error message to specific dimension (DHIS2-12915) v36

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/api/analytics.js
- yarn.lock
Implements [DHIS2-12580](https://jira.dhis2.org/browse/DHIS2-12580)
**Requires https://github.com/dhis2/analytics/pull/1238**
---
1. do now use weekly special handling with WEEKS_THIS_YEAR
---
The special weekly period handling does not work with this period,
because depending on the current date, it can happen that the same year
is used for fetching the data, instead of the requested years.
---
-   [x] bump `@dhis2/analytics` when https://github.com/dhis2/analytics/pull/1238 is merged
---
Before:
After:
> fix: use normal handling when WEEKS_THIS_YEAR is used in YoY DHIS2-12580

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/api/analytics.js
- yarn.lock
Implements [DHIS2-12580](https://jira.dhis2.org/browse/DHIS2-12580)
**Requires https://github.com/dhis2/analytics/pull/1246**
---
1. backport of #2065 
---
-   [x] update `analytics` to latest 20.x version
> fix: use normal handling when WEEKS_THIS_YEAR is used in YoY DHIS2-12580 (37.x)

- cypress/elements/chart.js
- cypress/integration/options/legend.cy.js
- cypress/utils/config.js
- packages/app/package.json
- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-12719](https://jira.dhis2.org/browse/DHIS2-12719)
**Requires https://github.com/dhis2/analytics/pull/1279**
---
1. _See Analytics PR for more info_
2. Updates Cypress tests to reflect the latest changes
3. Updates the History implementation to support the v5 syntax (@edoardo)
> fix: bump Analytics to latest + update Cypress + update history impl (DHIS2-12719)

- .github/workflows/cypress.yml
Pass `GITHUB_TOKEN` to Cypress test GH action, to prevent this bug from occuring: https://dhis2.atlassian.net/browse/CLI-36 (rerunning cypress on CI fails due to identical id)
> test: pass GITHUB_TOKEN as env param

- packages/app/src/actions/index.js
1. avoid encoding of visualization name in snackbar
---
Some characters like `/` are encoded by default by `i18n.t`.
We already instruct `i18n.t` to not encode the text when interpolating the variable in several places.
The visualization name should be safe.
---
Before:
After:
> fix: avoid encoding of visualization name in snackbar

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [[DHIS2-13475]](https://jira.dhis2.org/browse/DHIS2-13475)
**Requires https://github.com/dhis2/analytics/pull/1293**
---
1. bump analytics dependency for new functionality
---
See https://github.com/dhis2/analytics/pull/1289
> fix: bump @dhis2/analytics for tokens search support 38.x

- cypress/elements/chart.js
- cypress/integration/options/legend.cy.js
- cypress/utils/config.js
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport [DHIS2-12719](https://dhis2.atlassian.net/browse/DHIS2-12719) to 38.x
**Requires https://github.com/dhis2/analytics/pull/1311**
---
Partial cherry-pick from https://github.com/dhis2/data-visualizer-app/pull/2126
> fix: bump Analytics to latest + update Cypress (DHIS2-12719) 38.x

- cypress/elements/chart.js
- cypress/integration/options/legend.cy.js
- cypress/utils/config.js
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport [DHIS2-12719](https://dhis2.atlassian.net/browse/DHIS2-12719) to 37.x
**Requires https://github.com/dhis2/analytics/pull/1312**
---
Partial cherry-pick from https://github.com/dhis2/data-visualizer-app/pull/2126
> fix: bump Analytics to latest + update Cypress (DHIS2-12719) 37.x

- packages/plugin/src/VisualizationPlugin.js
Fixes [DHIS2-13812](https://jira.dhis2.org/browse/DHIS2-13812)
---
1. fix hidden PT plugin in dashboard
---
Dashboard app passed `height` and `width` in a `style` prop to the DV plugin.
A previous change to fix the same issue in the interpretation modal in DV app was overriding the `height` but caused the problem in dashboard app.
The fix is to use the passed value for `height` if available, and fallback to `100%`.
The former works for dashboard app while the latter works for the interpretation modal in DV.
---
Before:
After:
> fix: do not override height if present in style object DHIS2-13812

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Bumps Analytics to https://github.com/dhis2/analytics/pull/1345, which avoids using ES2022 function `.at` that was causing Cypress tests to fail
> fix: bump analytics to avoid es2022 fn 38.x

- cypress/utils/data.js
1. fix a failing Cypress test
---
The Gauge test is failing. Use a different AO.
> test: fix failing test, use a different Gauge AO

- cypress/integration/visTypes/scatter.cy.js
1. tweak the scatter test to avoid timeouts and consequent failures
---
This is a temporary fix for this test that started to fail on test instances when the facility levels for the whole Sierra Leone are requested.
There isn't a problem with the actual test, but on the current test instances the response consistently takes a very long time to return, causing this test to fail.
Also, wait for the org unit tree to be loaded before trying to select anything else than the root level, this seemed to fail consistently from my local testing.
---
Select the facility level only on a couple of org units:
> test: limit query scope to avoid long response time

- .github/workflows/dhis2-verify-app.yml
- cypress.json
- package.json
This PR doesn't have a JIRA ticket 😱 
The changes in this PR will ensure that both on CI and locally cypress will use the Chrome browser for runs. For interactive runs (i.e. `cypress open`) the browser will be headed and for regular runs it will be headless.
These changes should fix the issue that videos were not being recorded properly.
TODO:
> chore: always use chrome browser for cypress to record videos correctly

- cypress/elements/startScreen.js
- package.json
- yarn.lock
- Bumps Analytics to latest (for e.g. [DHIS2-6626](https://dhis2.atlassian.net/browse/DHIS2-6626))
- Log the server url in the beginning of each test (based on https://github.com/dhis2/line-listing-app/pull/312)
> fix: bump Analytics (DHIS2-6626)

- src/AppWrapper.js
1. do not initialise the old i18n with property files
---
i18n properties files have been removed already, but the `D2Shim` was still using `i18nRoot` which causes the app to try to load the property file for the current locale.
---
Failed request for old i18n property file:
> fix: remove old i18n initialisation

- package.json
- yarn.lock
@dhis2/ui lists styled-jsx as a peer dependency, and not having it in package.json results in a bunch of warnings during `yarn install`
> chore: add styled-jsx which is a peer dependency

- i18n/en.pot
- package.json
- src/components/VisualizationOptions/Options/DataIcon.js
- src/components/VisualizationPlugin/VisualizationPlugin.js
- src/modules/__tests__/current.spec.js
- src/modules/current.js
- src/modules/fields/baseFields.js
- src/modules/options.js
- src/modules/options/singleValueConfig.js
- yarn.lock
Implements [DHIS2-10496](https://jira.dhis2.org/browse/DHIS2-10496)
Requires: https://github.com/dhis2/analytics/pull/1440
---
1. implement option for showing data icon in SV
---
In maintenance app is possible to assign an icon to a data element, indicator, etc...
If an icon is assigned, when using the SV visualization type, it should be possible to see the icon together with the value.
This should be controlled via the options dialog.
---
Option in the Style tab for SV only:
Example of SV with icon:
[DHIS2-10496]: https://dhis2.atlassian.net/browse/DHIS2-10496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implement data icon option for SV visualization (DHIS2-10496)

- cypress/elements/dimensionModal/orgUnitDimension.js
- cypress/elements/fileMenu/open.js
- cypress/elements/startScreen.js
- cypress/support/utils.js
Adds `EXTENDED_TIMEOUT` to the File Open modal to prevent timing out when the list of AOs is slow to load while testing.
> test: add extended timeout for file open modal

- src/components/Visualization/Visualization.js
Implements [DHIS2-15243](https://jira.dhis2.org/browse/DHIS2-15243)
---
1. Throw same error for case `E7113` as for case `E7114`
---
Throws the same custom error message for case `E7113` (DE and non-DE used with AC) as for case `E7114` (non-DE used with AC), as they essentially have the same solution (make sure that only DE's are used with AC).
---
_the custom error being thrown_
[DHIS2-15243]: https://dhis2.atlassian.net/browse/DHIS2-15243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ac with a non-data element throws backend error instead of custom error

- package.json
- yarn.lock
Implements [LIBS-499](https://jira.dhis2.org/browse/LIBS-499)
[LIBS-499]: https://dhis2.atlassian.net/browse/LIBS-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump cli-app-scripts to 10.3.8 for LIBS-499 fix

- cypress/elements/dimensionModal/dataDimension.js
- cypress/elements/dimensionModal/index.js
- cypress/elements/dimensionModal/periodDimension.js
- cypress/integration/dimensions/data.cy.js
- cypress/integration/dimensions/period.cy.js
There's been a long running issue with the `Transfer` component showing stale items after applying a filter. This seems to be due to the way Cypress uses cache to store an element (which makes it stale when the element content has changed).
This solution hopefully fixes this for good, by switching to a different method for evaluating the list of items in the `Transfer` component.
> test: prevent items in transfer from being stale when filtering

- cypress/elements/chart.js
extends the timeout for when visualizations are loading since that seems to be slow sometimes (which could be because of the server), e.g. this test failed when trying to open a PR because the result didn't return fast enough https://cloud.cypress.io/projects/sojh88/runs/2000/test-results/834f2e45-c119-4b4f-9c08-d7f95653be2b
> test: extend timeout for loading visualizations

- .github/workflows/dhis2-verify-app.yml
Tag builds were not being pushed to d2-ci. The core apps-to-bundle depends on these.
> chore: run workflow release job on tags as well

- cypress/elements/chart.js
- cypress/elements/dimensionModal/dataDimension.js
- cypress/elements/dimensionModal/index.js
- cypress/elements/dimensionModal/periodDimension.js
- cypress/elements/optionsModal/legend.js
- cypress/integration/dimensions/data.cy.js
- cypress/integration/dimensions/period.cy.js
- cypress/integration/options/icon.cy.js
- package.json
- src/components/TitleBar/TitleBar.js
- src/components/VisualizationOptions/Options/DataIcon.js
- yarn.lock
Implements [DHIS2-10496](https://jira.dhis2.org/browse/DHIS2-10496)
**Requires https://github.com/dhis2/analytics/pull/1479**
---
Adds Cypress tests for SV icon
Also, copies changes from #2321 and #2368 as these were incorrectly targeting `master` instead of `dev`
[DHIS2-10496]: https://dhis2.atlassian.net/browse/DHIS2-10496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: add Cypress tests for SV icon (DHIS2-10496)

- cypress/elements/chart.js
- cypress/support/index.js
- src/components/TitleBar/TitleBar.js
Implements [DHIS2-15063](https://dhis2.atlassian.net/browse/DHIS2-15063)
---
Renames `AO-title` to `titlebar` for consistency with other apps
Also, prevents ResizeObserver from failing the tests by utilising the check used in Dashboard - [dashboard-app/blob/dev/cypress/support/index.js#L12](https://github.com/dhis2/dashboard-app/blob/dev/cypress/support/index.js#L12)
[DHIS2-15063]: https://dhis2.atlassian.net/browse/DHIS2-15063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: rename AO-title to titlebar (DHIS2-15063)

- cypress/elements/calculationsModal.js
- cypress/elements/dimensionModal/dataDimension.js
The `expectNoDataItemsToBeSelected` fails after delete has been triggered if the delete action takes longer than 4s, as seen in the test run here https://cloud.cypress.io/projects/sojh88/runs/3b386e3c-bd60-4ced-88fd-b17c90920846/test-results/c436fb6d-a505-4de0-b8e3-dd449b688a82/video
This PR adds the `EXTENDED_TIMEOUT` to prevent this by validating that the calculation modal has been closed.
> test: extend timeout after delete has been triggered

- cypress.json
- cypress/elements/dimensionModal/dataDimension.js
- cypress/elements/dimensionModal/index.js
- cypress/integration/dimensions/data.cy.js
- cypress/support/utils.js
based on https://github.com/dhis2/maps-app/pull/2720
We seem to get random failures pretty regularly and they are often caused by slow instance. This will increase the default timeout for all DOM activity, which I hope will alleviate some of this.
> chore: increase cypress default timeout for DOM activity

- .github/dependabot.yml
- package.json
- src/modules/options/gaugeConfig.js
- src/modules/options/pieConfig.js
- src/modules/options/pivotTableConfig.js
- src/modules/options/scatterConfig.js
- src/modules/options/sections/advanced.js
- src/modules/options/sections/colorSet.js
- src/modules/options/sections/domainAxis.js
- src/modules/options/sections/lines.js
- src/modules/options/sections/rangeAxis.js
- src/modules/options/sections/titles.js
- src/modules/options/singleValueConfig.js
- src/modules/options/tabs/legend.js
- src/modules/options/tabs/limitValues.js
- src/modules/options/tabs/series.js
- yarn.lock
Manual override for the following dependabot PRs
Implemented:
https://github.com/dhis2/data-visualizer-app/pull/2266 - enzyme-adapter-react-16
https://github.com/dhis2/data-visualizer-app/pull/2263 - start-server-and-test
https://github.com/dhis2/data-visualizer-app/pull/2262 - @dhis2/cli-style
https://github.com/dhis2/data-visualizer-app/pull/2264 - redux-thunk
https://github.com/dhis2/data-visualizer-app/pull/2267 - react-beautiful-dnd
https://github.com/dhis2/data-visualizer-app/pull/2218 - decode-uri-component
https://github.com/dhis2/data-visualizer-app/pull/2258 - query-string
https://github.com/dhis2/data-visualizer-app/pull/2259 - redux-actions
https://github.com/dhis2/data-visualizer-app/pull/2275 - patch-package
Rejected:
https://github.com/dhis2/data-visualizer-app/pull/2337 - …
> chore: manually bump deps

- cypress/integration/options/axes.cy.js
- cypress/integration/options/fontStyles.cy.js
When a test case name is dynamic and based on a non-persistent variable, such as a randomly generated number, the Cypress dashboard will pick these tests up as a new test case and mark it with `First seen`. This can potentially disturb the test statistics for e.g. flaky tests (as each run generates "new" test cases which can't be compared between different runs). See example screenshot below.
Keeping track of a generated value is good for debugging, but instead of displaying it the name it will now be logged in the beginning of the test case.
_Example of test cases showing up as `First seen` due to having a randomly generated number in the name_
> test: prevent test names from being dynamic

- src/components/App.js
- src/components/VisualizationPlugin/VisualizationPlugin.js
Implements [DHIS2-15721](https://dhis2.atlassian.net/browse/DHIS2-15721)
---
1. Allow closing the interpretations modal when accessed from URL
---
There were actually two separate problems that needed fixing:
1. The main problem, which actually impacted the functionality was that when closing the modal, the interpretations panel on the right of the main page would always update. When accessing the interpretation via the URL, the panel on the right is actually closed (not in the DOM), so the ref to call `refresh` on was undefined. This would prevent the modal from closing.
2. When closing the modal, the resize-observer's callback would be called, which caused a state update on the `VisualizationPlugin` component, and this then triggered React to show a `console.error` message about …
> fix: allow closing the interpretations modal when accessed via URL (DHIS2-15721)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-14511](https://jira.dhis2.org/browse/DHIS2-14511)
**Requires https://github.com/dhis2/analytics/pull/1585**
---
1. fix undefined in PT totals when value is 0 (bump analytics dependency)
---
Backport.
See original fix [here](https://github.com/dhis2/analytics/pull/1552).
[DHIS2-14511]: https://dhis2.atlassian.net/browse/DHIS2-14511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: avoid undefined in totals (DHIS2-14511) [v38]

- package.json
- packages/app/package.json
- packages/plugin/package.json
1. bump version to unlock release
---
Release of 39.2.10 failed because the tag for it is already present.
Latest release was 39.2.15.
Bumping the version to 39.2.15 should unlock the semantic release process and 39.2.16 should be published.
> fix: bump version to release 39.2.16

- cypress/elements/chart.js
- cypress/elements/common.js
- cypress/elements/optionsModal/fontStyles.js
- cypress/elements/optionsModal/index.js
- cypress/elements/optionsModal/legend.js
- cypress/integration/options/fontStyles.cy.js
- cypress/integration/options/legend.cy.js
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/TextStyle.js
- packages/app/src/modules/options/singleValueConfig.js
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-14535](https://jira.dhis2.org/browse/DHIS2-14535)
---
1. fix URL in GetLink dialog
---
The fix is actually in `@dhis2/analytics`. This PR is for bumping the dependency to the correct version with the fix.
---
Before:
After:
[DHIS2-14535]: https://dhis2.atlassian.net/browse/DHIS2-14535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: avoid duplicate path in get link URL DHIS2-14535 [v39]

- cypress/integration/save.cy.js
- src/actions/index.js
Fixes [DHIS2-15722](https://dhis2.atlassian.net/browse/DHIS2-15722)
**Requires https://github.com/dhis2/analytics/pull/1573**
---
1. fix a bug that caused a newly copied visualization to be deleted when saving it again
---
Refer to the ticket for the explanation on why it happened.
The PR fixes the issue by cleaning up the payload passed to the POST request for copying an existing visualization.
[DHIS2-15722]: https://dhis2.atlassian.net/browse/DHIS2-15722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
> fix: visualization deleted when saving it after copy DHIS2-15722

- .github/workflows/dhis2-verify-app.yml
- cypress/integration/confirmLeave.cy.js
- cypress/integration/new.cy.js
- cypress/integration/save.cy.js
- cypress/integration/start.cy.js
To follow [cypress best practice](https://docs.cypress.io/guides/references/best-practices#Creating-Tiny-Tests-With-A-Single-Assertion), consolidate assertions into single tests when they represent a single logical user journey
Positive side effects (in addition to those listed in the best practice page):
- less tests contributing to our monthly cypress subscription total
- less skewed impression of coverage
With these changes the number of tests has gone down from 637 to 569
> chore: consolidate cypress tests

- .github/workflows/dhis2-verify-app.yml
- cypress.config.js
- package.json
- yarn.lock
Now you will be able to:
- see all the cypress tests merged in one Report portal launch
- find a launch by : 
- PR_TITLE
- BRANCH_NAME
- CI_BUILD_ID
Part of the work was done at the level of : 
- https://github.com/dhis2/agent-js-cypress/commit/d3afea4e74abdbef39c1121f820f23deca2368f4
- https://github.com/dhis2/workflows/pull/46
- https://github.com/dhis2/workflows/pull/47
> chore: use reportportal fork

- jest.config.js
Remove testRegex from Jest config to revert to default jest test file detection
> chore: remove testRegex from jest config to revert to default test file detection

- package.json
- src/components/DownloadMenu/GraphicsMenu.js
- src/components/DownloadMenu/TableMenu.js
- src/components/DownloadMenu/ToolbarDownloadDropdown.js
- yarn.lock
Implements: No issue number available
**Requires https://github.com/dhis2/analytics/pull/1620**
---
1. Adds class-names to elements that push-analytics need to interact with
---
-   [x] Wait for https://github.com/dhis2/analytics/pull/1620 to be merged and bump analytics version
> feat: add class-names for push-analytics

- .github/workflows/dhis2-verify-app.yml
It is useful to see the release notes in the slack channel for a quick reference as to what was released.
The commit message in the "chore(release)" commit includes the release notes, so hopefully it will display nicely.
This is an example of what it will look like (except obviously it will say "Data Visualizer app":
> chore: include release notes in slackbot message

- cypress/elements/dimensionsPanel.js
- cypress/integration/dimensions/data.cy.js
- cypress/integration/dimensions/dynamic.cy.js
(cherry picked from commit 1156a51bf3864e22a5e6ed595722c4680f5d0333)
> test: adapt tests to new database v38

- public/push-analytics.json
Related to [DHIS2-15367](https://dhis2.atlassian.net/browse/DHIS2-15367) in JIRA and push-analytics [PR#10](https://github.com/dhis2/push-analytics/pull/10)
---
1. Adds a JSON file with scrape instructions which push-analytics can use to convert a dashboard item for this app.
---
[DHIS2-15367]: https://dhis2.atlassian.net/browse/DHIS2-15367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(push-analytics): add push analytics instructions

- .github/workflows/dhis2-verify-app.yml
For the 41 soft freeze period, the app bundle needs to be deployed to d2-ci. Since branch 'dev' will be used to build the core bundle, run the release job on both master and dev branches
> chore: run the release step on both dev and master branches

- package.json
- src/components/VisualizationOptions/Options/OutliersMaxResults.js
- src/components/VisualizationPlugin/VisualizationPluginWrapper.js
- yarn.lock
1. show the loading spinner in dashboard while waiting for analytics data
2. don't allow clearing `maxResults` value
---
The spinner was never enabled, the fix avoids a blank looking dashboard item when analytics takes some time.
If you were clearing the value for the `maxResults` option, a 400 error was returned from the outlierDetection api because `NaN` was passed as value for the option.
The allowed range is 1-500, the fix makes sure it's not possible to clear the value.
---
> fix: show loading spinner while waiting for data

- src/api/analytics.js
- src/components/VisualizationPlugin/VisualizationPluginWrapper.js
Part of [DHIS2-13858](https://jira.dhis2.org/browse/DHIS2-13858)
---
1. ensure only the 1st item selected for the period is used
2. enable the loading spinner when plugin props change
---
When applying filters in dashboard, it's possible to select more than 1 item for the period.
Outlier table only allows for 1 period item.
The fix is to always only use the 1st item for the period dimension, otherwise the outlier api returns an error.
When applying a filter in dashboard, the loading spinner of the plugin didn't trigger.
The fix enabled the loading spinner whenever the plugin props are updated, which causes a re-render of the visualization in the plugin.
---
Period filter before:
Period filter after:
Loading before:
Loading after:
[DHIS2-13858]: …
> fix: fix period filter and loading spinner when filtering in dashboard

- packages/app/package.json
- yarn.lock
Fixes https://dhis2.atlassian.net/browse/DHIS2-15825 and https://dhis2.atlassian.net/browse/DHIS2-16365
Requires https://github.com/dhis2/analytics/pull/1642
This PR supersedes https://github.com/dhis2/data-visualizer-app/pull/2892
Key features
1. Show correct date and time in About AO Unit in interpretations panel
2. Preserve newlines in interpretations and replies
(yarn-deduplicate was run to make sure that plugin also uses the 24.10.3 version of analytics.)
Other changes since analytics was last updated:
1. feat: single value background color change based upon legend (DHIS2-13702)
2. fix: sv size when downloading is a small square (DHIS2-15178)
3. fix: avoid undefined in totals DHIS2-14511
Screenshot shows chart was just created. Timestamp is "a few seconds ago", rather than "1 hour …
> fix: about AO showed wrong datetime, newlines in interpretations and replies not preserved [v39]

- cypress/integration/save.cy.js
- cypress/integration/start.cy.js
- packages/app/src/components/MenuBar/MenuBar.js
Backport of the fix for [DHIS2-15373](https://jira.dhis2.org/browse/DHIS2-15373)
---
1. disable Save button when visualization is not in unsaved/dirty state
---
See https://github.com/dhis2/data-visualizer-app/pull/2758
[DHIS2-15373]: https://dhis2.atlassian.net/browse/DHIS2-15373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disable Save when vis not in unsaved/dirty state (DHIS2-15373) v39

- .github/workflows/cypress.yml
- cypress/integration/save.cy.js
- cypress/integration/start.cy.js
- packages/app/package.json
- packages/app/src/components/MenuBar/MenuBar.js
- packages/plugin/package.json
- yarn.lock
Backport of the fix for [DHIS2-15373](https://jira.dhis2.org/browse/DHIS2-15373)
---
1. disable Save button when visualization is not in unsaved/dirty state
---
See https://github.com/dhis2/data-visualizer-app/pull/2758
[DHIS2-15373]: https://dhis2.atlassian.net/browse/DHIS2-15373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disable Save when vis not in unsaved/dirty state DHIS2-15373 v38

- cypress/elements/pivotTable.js
- cypress/integration/options/totals.cy.js
- package.json
- yarn.lock
Implements [DHIS2-17297](https://jira.dhis2.org/browse/DHIS2-17297)
**Requires https://github.com/dhis2/analytics/pull/1660**
---
1. the actual fix is in `analytics`
---
See [the ticket](https://jira.dhis2.org/browse/DHIS2-17297) and the [analytics' PR description](https://github.com/dhis2/analytics/pull/1660).
---
-   [x] Cypress tests
-   [x] Manual testing
---
Before:
After:
[DHIS2-17297]: https://dhis2.atlassian.net/browse/DHIS2-17297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix a crash when row totals is enabled (DHIS2-17297)

- .github/workflows/dhis2-verify-app.yml
There is no reason to run the release step on the dev branch. Only master and tag builds are needed for bundles.
> chore: do not run release step on dev branch

- package.json
- yarn.lock
Implements [DHIS2-16172](https://jira.dhis2.org/browse/DHIS2-16172)
**Requires https://github.com/dhis2/analytics/pull/1677**
---
See Analytics PR for info and screenshots
[DHIS2-16172]: https://dhis2.atlassian.net/browse/DHIS2-16172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: separator for hundreds, thousands and millions is missing in the Pie charts (DHIS2-16172)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-16172](https://jira.dhis2.org/browse/DHIS2-16172)
**Requires https://github.com/dhis2/analytics/pull/1679**
---
Backport of https://github.com/dhis2/data-visualizer-app/pull/3093 to 39
[DHIS2-16172]: https://dhis2.atlassian.net/browse/DHIS2-16172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: separator for hundreds, thousands and millions is missing in the Pie charts (DHIS2-16172) v39

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-14028](https://dhis2.atlassian.net/browse/DHIS2-14028)
The `PivotTable` in `@dhis2/analytics` no longer has global styles that bleed out of the component. It now uses scoped styles instead, which is much better in general. However, since plugins are in iframes from version 40 onwards, this fix is only required for this v39 branch.
Once this is merged and a new version is released, https://github.com/dhis2/dashboard-app/pull/3014 needs to be updated to use that new version for the data-visualizer-plugin dependency.
---
[DHIS2-14028]: https://dhis2.atlassian.net/browse/DHIS2-14028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade @dhis2/analytics for scoped pivot table styles v39

- src/components/InterpretationModal/InterpretationModal.js
Implements [DHIS2-15894](https://dhis2.atlassian.net/browse/DHIS2-15894)
---
Use saved visualization in interpretation modal instead of current (dirty) visualization
[DHIS2-15894]: https://dhis2.atlassian.net/browse/DHIS2-15894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use saved visualization in interpretation modal

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport for [DHIS2-16904](https://jira.dhis2.org/browse/DHIS2-16904)
See [original PR](https://github.com/dhis2/data-visualizer-app/pull/3124).
[DHIS2-16904]: https://dhis2.atlassian.net/browse/DHIS2-16904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump analytics with fix for DHIS2-16904 v39

- package.json
- yarn.lock
The version mentioned in the resolutions was lower than the one in the dependencies. This was unintentional.
> chore: resolve to @dhis2/ui 9.4.4

- cypress/elements/visualizationTypeSelector.js
- cypress/integration/dimensions/calculations.cy.js
- cypress/integration/dimensions/dynamic.cy.js
- cypress/integration/dimensions/orgUnit.cy.js
- cypress/integration/drillDown.cy.js
- cypress/integration/options/axes.cy.js
- cypress/integration/options/fontStyles.cy.js
- cypress/integration/options/legend.cy.js
- cypress/integration/options/lines.cy.js
- package.json
- yarn.lock
Implements [DHIS2-15833](https://jira.dhis2.org/browse/DHIS2-15833)
**Requires https://github.com/dhis2/analytics/pull/1694**
-   [x] Cypress tests
-   Update docs - not needed
-   [x] Manual testing
---
See https://github.com/dhis2/analytics/pull/1694 for video.
[DHIS2-15833]: https://dhis2.atlassian.net/browse/DHIS2-15833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: pivot table as default vis type in DV (DHIS2-15833)

- package.json
- yarn.lock
Implements [DHIS2-17861](https://jira.dhis2.org/browse/DHIS2-17861)
**Requires https://github.com/dhis2/analytics/pull/1695**
[DHIS2-17861]: https://dhis2.atlassian.net/browse/DHIS2-17861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: sort analytics request params and items for cache hit optimization (DHIS2-17861)

- src/components/DimensionsPanel/DndDimensionItem.js
- src/components/DimensionsPanel/styles/DndDimensionItem.module.css
- src/components/Layout/Chip.js
- src/components/Layout/styles/Chip.module.css
Implements [DHIS2-15140](https://dhis2.atlassian.net/browse/DHIS2-15140)
---
1. Updates cursor style for assigned categories dimension item
---
| When/where | Style rule | Screenshot |
| ------------- | ------------- | ------------- |
| Sidebar unselected  | `cursor: grab;`  | <img width="243" alt="sidebar_unselected" src="https://github.com/user-attachments/assets/4d01e9c6-4470-478d-92a9-3c2ea849c4c8"> | 
| Sidebar selected  | `cursor: default;`  | <img width="247" alt="sidebar_selected" src="https://github.com/user-attachments/assets/dd53b60d-b119-4d6c-b6fa-9fd61e77f454"> | 
| Layout  | `cursor: grab;`  | <img width="238" alt="layout" src="https://github.com/user-attachments/assets/83c7ed42-9fef-4aa1-90b6-bddfa3afb44a"> | 
[DHIS2-15140]: …
> fix: apply grab cursor to assigned categories dimension item

- cypress.config.js
- src/components/VisualizationOptions/Options/Subtitle.js
- src/modules/options/pivotTableConfig.js
Implements [DHIS2-16158](https://dhis2.atlassian.net/browse/DHIS2-16158)
---
1. Adds subtitle field to pivot table style options
---
On the style tab of the pivot table options, a user can now set a subtitle as well as a title (title was already implemented). I have verified that the subtitle is displayed in the pivot table correctly, and it is persisted correctly too.
---
-   There is no Cypress test for this new feature. I decided not to add one, because hardly any of these options are tested. For example, the title is not tested either. So I assumed that at some point we must have decided that tests for these options are not required.
---
Option modal:
Pivot table:
[DHIS2-16158]: https://dhis2.atlassian.net/browse/DHIS2-16158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> feat: add subtitle field to pivot table options [DHIS2-16158]

- src/components/VisualizationPlugin/VisualizationPlugin.js
No JIRA issue. This change makes the icons fetching logic more robust:
1. It fetches the icon with credentials which prevents a 500 error on certain versions of the backend
2. If any other response code than 200 is returned, we return a string that can be parsed into an empty icon. This is better than trying to build an SVG from a string that is really a stringified error code / error message 🤣
> fix: fetch icon with credentials

- src/components/Visualization/StartScreen.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/VisualizationErrorInfo.js
- src/components/Visualization/styles/StartScreen.module.css
- src/components/Visualization/styles/VisualizationErrorInfo.module.css
- src/components/VisualizationPlugin/VisualizationPluginWrapper.js
- src/modules/analytics.js
Implements [DHIS2-16793](https://jira.dhis2.org/browse/DHIS2-16793)
---
1. Adds some validation to the plugin wrapper so that it won't attempt to render a visualization when there is no data
---
The key feature needs no further explanation but there are some things to take into consideration about the implementation:
- The JIRA issue mentions a bug in the `PivotTable` component, and this is indeed where the error is thrown. However, this is really going wrong at an earlier stage: the filter condition has caused the rows to be empty, and really the plugin shouldn't have rendered the `PivotTable` in the first place, but some sort of info/error screen instead. So this is what I have addressed, and I have ignored the bug in the `PivotTable`. I am not sure we need to address this one.
- The …
> fix: show error UI when plugin has empty rows [DHIS2-16793]

- jest.config.js
Jest tests were not run successfully for dependabot PRs because of the reportportal needing repository secrets. 
Therefore replicating the reportportal config that Adel added to other analytics repos
> chore: do not use reportportal when dependabot PR

- cypress/integration/interpretations.cy.js
- src/components/VisualizationPlugin/VisualizationPluginWrapper.js
Fixes [DHIS2-18369](https://dhis2.atlassian.net/browse/DHIS2-18369)
The InterpretationsModal callback onResponsesReceived was not being called after a recent fix introduced its own onResponsesReceived callback
-   [x] Cypress tests
-   [x] Manual testing
-   [x] Retest original bug fix [DHIS2-16793](https://dhis2.atlassian.net/browse/DHIS2-16793)
-   [x] Dashboard tested
---
[DHIS2-18369]: https://dhis2.atlassian.net/browse/DHIS2-18369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-16793]: https://dhis2.atlassian.net/browse/DHIS2-16793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: infinite spinner when opening the interpretations modal while viewing a visualization

- cypress/elements/chart.js
- cypress/elements/optionsModal/index.js
- cypress/elements/optionsModal/legend.js
- cypress/integration/options/legend.cy.js
- package.json
- src/components/VisualizationPlugin/ChartPlugin.js
- src/components/VisualizationPlugin/__tests__/ChartPlugin.spec.js
- yarn.lock
No issue number available
**Note for efficient reviewing**
This code includes quite a few changes. However, the vast majority of changes were cherry picked from branch #3135, which had already been reviewed. The only file I edited manually was `src/components/VisualizationPlugin/ChartPlugin.js`.
---
1. Handles the single value visualization as a `Highcharts.Chart` instance, which it is since `@dhis2/analytics` version `26.9.0`
2. This new implementation will allow us to do client-side exports using Highchart's `Chart.exportChartLocal` (IN THE FUTURE, NOT NOW)
3. Instead of computing the font-size directly on the canvas size, this new implementation scales in steps. This reduces the problem of multiple single value items in a single dashboard all showing a different font-sizes.
---
-   [x] …
> fix: handle single value vis-type as highcharts chart instance

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-14827](https://dhis2.atlassian.net/browse/DHIS2-14827)
This feature was implemented fully in @dhis2/analytics so all we need in DV is a version bump.
The PR against the dev branch (https://github.com/dhis2/data-visualizer-app/pull/2858) was closed because the analytics version there got bumped in another merged PR.
---
1. Because we now truncate the title, long filters won't stretch the table horizontally anymore
2. Once the title gets truncated a tooltip will be available for users to see the full title
---
[DHIS2-14827]: https://dhis2.atlassian.net/browse/DHIS2-14827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: upgrade analytics to get pivot table truncated title feature [v39] [DHIS2-14827]

- .github/workflows/e2e-dev.yml
1. add Github workflow for running e2e tests on dev
---
The workflow allows to run e2e tests against the dev instance when the `e2e dev` label is added to a PR.
It is copied from dashboard app.
> chore: add e2e dev workflow

- cypress/support/e2e.js
1.use enableAutoLogin for handling login correctly
---
The .action endpoint has been removed in 42.
The enableAutoLogin function from cypress-commands handles correctly the login for different instance versions.
> chore: use enableAutoLogin for handling Cypress login correctly

- src/actions/index.js
- src/components/Visualization/Visualization.js
Implements [DHIS2-19187](https://dhis2.atlassian.net/browse/DHIS2-19187)
---
1. fix regression with Not found error not showing up
---
If a visualization is not found due to using an outdated link or a wrong id in the URL, a custom message should be shown informing about it.
Since v101.0.0 this stopped working.
The culprit was a change introduced when refactoring the error handling.
---
---
---
Before:
After:
[DHIS2-19187]: https://dhis2.atlassian.net/browse/DHIS2-19187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix regression in Not found visualization error (DHIS2-19187)

- .github/pull_request_template.md
- package.json
- yarn.lock
Implements [DHIS2-19274](https://dhis2.atlassian.net/browse/DHIS2-19274)
**Requires https://github.com/dhis2/analytics/pull/1770**
---
Hyperlinks in the Visualization description as well as interpretations were not opening if the global shell (42.0 feature) was enabled. This also includes the "Get link" file menu option.
---
App can be tested at  https://test.e2e.dhis2.org/analytics-42dev
[DHIS2-19274]: https://dhis2.atlassian.net/browse/DHIS2-19274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ensure hyperlinks work when using the upcoming global shell [DHIS2-19274]

- src/components/App.js
Implements [DHIS2-19387](https://dhis2.atlassian.net/browse/DHIS2-19387)
Manual URL changes trigger location updates with the key `default`, which then results in the `history` skipping its handler because it's the same as the key as the previous updates
It's still important to check they `key` to avoid triggering the handler multiple times for the same location update, but the pathname and search can be checked to see if the rest of the handler should run
https://github.com/user-attachments/assets/b23326ad-c723-4798-94d4-cee609c94036
[DHIS2-19387]: https://dhis2.atlassian.net/browse/DHIS2-19387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:  restore navigation between visualizations using the browser address bar [DHIS2-19387]

- .github/workflows/dhis2-preview-pr.yml
- .github/workflows/dhis2-verify-commits.yml
1. remove deprecated package used in GHA
---
See: 
https://github.com/c-hive/gha-yarn-cache?tab=readme-ov-file#deprecated
https://github.com/actions/toolkit/blob/main/packages/cache/README.md
> chore: remove use of deprecated cache package in GHA

- src/components/Visualization/styles/Visualization.style.js
Fixes [DHIS2-19533](https://dhis2.atlassian.net/browse/DHIS2-19533)
This PR changes the background color of the visualization canvas `loading` cover to match the standard app background color.
---
Add _N/A_ to items that are not applicable.
- [ _N/A_ ] Dashboard tested
- [ _N/A_ ] Cypress and/or Jest tests added/updated
- [ _N/A_ ] Docs added
- [ _N/A_ ] d2-ci dependency replaced (requires https://github.com/dhis2/analytics/pull/XXX)
---
Before: 
After:
[DHIS2-19533]: https://dhis2.atlassian.net/browse/DHIS2-19533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: visualization canvas loading background (DHIS2-19533)

- d2.config.js
No issue NR available
Based on a conversation I had today I have created this PR, but I have to admit I am not quite sure that the changes I have just done are all that's required.
Let me start by adding a few quotes:
> Will this significantly increase PWA install size? 
> I believe this would increase the install size by default; I think it would make sense to use the `pwa.caching.globsToOmitFromPrecache` [option](https://developers.dhis2.org/docs/app-platform/pwa/#opting-in) in `d2.config.js` to not cache them on install :slightly_smiling_face: I think the Maps app does this for some fonts
So that's what I did, but I also looked at the `d2.config.js` in maps and this has a pretty long regex 
to populate `patternsToOmitFromAppShell`. I am wondering if this is just a completely unrelated …
> fix: prevent font files from being pre-cached
