dhis2/data-visualizer-app

- .travis.yml
- yarn.lock
Deployment will be added later
> Add travis.yml file with code climate and build configured

- .travis.yml
- package.json
Related to: https://github.com/dhis2/dhis2-core/pull/2185
> Add deploy-build so Travis deploys each build to a `package-builds` repo

- packages/app/src/actions/ui.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
Enable support for updating ui `itemsByDimension` object partially.
> task/Implement redux reducer, action and test for ADD_UI_ITEMS action

- packages/app/src/actions/index.js
- packages/app/src/actions/metadata.js
- packages/app/src/configureStore.js
- packages/app/src/index.js
- packages/app/src/middleware/metadata.js
- packages/app/src/reducers/__tests__/metadata.js
- packages/app/src/reducers/index.js
- packages/app/src/reducers/metadata.js
- packages/app/src/storeDesign.js
- Adds new store prop: "metadata" (reducer, action creator, test)
- Adds middleware that listens to "metadata" props in actions
> Store metadata

- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/Menu.js
- packages/app/src/components/Layout/Tooltip.js
- packages/app/src/reducers/metadata.js
Shows item names in a tooltip on hover. It's a Popper rather than a Tooltip as the latter is just an html "title" attribute which does not support html or line breaks.
- show delay: 500
- hide on mouse leave, click and drag
- show "None selected" for empty dimensions
> Dimension item popup

- packages/app/src/__tests__/util.spec.js
- packages/app/src/actions/dimensions.js
- packages/app/src/util.js
Also fixes error in data dimension (SELECT ALL)
[DHIS2-4944]
> Keep arrayToIdMap pure, sort separately if needed

- packages/app/src/actions/index.js
- packages/app/src/actions/settings.js
- packages/app/src/api/settings.js
- packages/app/src/components/App.js
- packages/app/src/index.js
- packages/app/src/reducers/__tests__/settings.spec.js
- packages/app/src/reducers/index.js
- packages/app/src/reducers/settings.js
- packages/app/src/settings.js
- Passing down userSettings from index to App
- Fetching systemSettings + merging userSettings before dispatching all settings to the store in one go
> Load and add system/user settings to the store

- packages/app/src/components/App.css
- packages/app/src/components/App.js
- packages/app/src/components/Dimensions/DimensionLabel.js
- packages/app/src/components/Dimensions/styles/DimensionLabel.style.js
- packages/app/src/components/Dimensions/styles/DimensionOptions.style.js
- packages/app/src/components/Dimensions/styles/Dimensions.style.js
- packages/app/src/components/MenuBar/MenuBar.css
- packages/app/src/components/MenuBar/MenuBar.js
- packages/app/src/components/MenuBar/UpdateButton.js
- packages/app/src/components/MenuBar/styles/MenuBar.style.js
- packages/app/src/components/MenuBar/styles/UpdateButton.style.js
- packages/app/src/components/Visualization/BlankCanvas.js
- packages/app/src/components/VisualizationOptions/VisualizationOptionsManager.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/icons.js
A bunch of style fixes to the menubar, chart type selector and dimensions list.
> Demo readify ui

- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/AggregationType.js
- packages/app/src/options.js
- yarn.lock
d2.analytics makes sure the aggregationType option is not added to the
request if the value is DEFAULT.
We need to handle the DEFAULT value for the option in the AO for backwards
compatibility.
> Use DEFAULT as default value for aggregationType

- packages/app/src/actions/ui.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
Add action, reducer and reducer test for store.ui.activeModalDialog.
> Add store.ui.activeModalDialog

- packages/app/i18n/en.pot
- packages/app/package.json
- yarn.lock
It seems that a conflict in MUI versions was causing a crash with the File->Open and File->Save in the file menu.
> fix/Upgrade period-selector-dialog that was causing file->open crash

- packages/app/src/components/Layout/YearOnYearLayout/YearOnYearAxis.js
- packages/app/src/components/Layout/YearOnYearLayout/YearOnYearLayout.js
- packages/app/src/components/Layout/YearOnYearLayout/YearOnYearSelect.js
- packages/app/src/components/Layout/YearOnYearLayout/styles/YearOnYearAxis.style.js
- packages/app/src/components/Layout/YearOnYearLayout/styles/YearOnYearLayout.style.js
- packages/app/src/components/Layout/YearOnYearLayout/styles/YearOnYearSelect.style.js
- packages/app/src/modules/yearOnYear.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
- Add drop down flex
- Add fixed years
- Add multiselect component
> Fixed years in YOY chart

- packages/app/src/components/Layout/styles/Chip.style.js
- packages/app/src/components/Layout/styles/style.js
Not sure why it was broken after merging master...
> Fix styles for chips in layout

- config/shim.js
- packages/app/package.json
- add shims for global variables used for dev mode in headerbar beta
- update app version to match the d2 version
- update ui build path to d2-ci
> Fix broken build

- packages/app/src/modules/theme.js
This removes the deprecation warning in console
> fix/configure MUI typography variant version to v2

- packages/app/package.json
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/YearOnYearLayout/YearOnYearLayout.js
- packages/app/src/modules/fields/baseFields.js
- packages/app/src/modules/ui.js
- packages/app/src/modules/yearOnYear.js
- packages/app/src/reducers/__tests__/current.spec.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/current.js
- packages/app/src/reducers/ui.js
- yarn.lock
Keep the store.ui format and create other formats by type on the fly when needed.
> Year on year store.ui format

- packages/app/src/components/App.css
- packages/app/src/components/App.js
- packages/app/src/components/TitleBar/TitleBar.js
- packages/app/src/components/TitleBar/__tests__/TitleBar.spec.js
- packages/app/src/components/TitleBar/styles/TitleBar.style.js
- packages/app/src/widgets/SnackbarMessage.js
> TitleBar component

- packages/app/i18n/en.pot
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/Interpretations/InterpretationsButton.js
- packages/app/src/components/MenuBar/MenuBar.js
- packages/app/src/components/TitleBar/TitleBar.js
- packages/app/src/components/TitleBar/__tests__/TitleBar.spec.js
- packages/app/src/components/TitleBar/styles/TitleBar.style.js
- packages/app/src/modules/storeDesign.js
- packages/app/src/reducers/current.js
- yarn.lock
- Change default store.ui.current value to null
- Show "Unsaved chart" when chart is not saved
- Show " - Edited" instead of asterisk
- Update tests
> Fix titlebar

- packages/app/src/api/analytics.js
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- DHIS2-5192: icons for plain data source download options
- DHIS2-5228: fix for download base URL
- DHIS2-5230: fix spelling of Metadata
> Fixes in download menu

- packages/app/src/api/dimensions.js
- packages/app/src/modules/dataSets.js
- packages/app/src/modules/dataTypes.js
- Fix wrongly named reporting rate metric constants
- Add order when requesting dimension items
> Pass "order" in dimension item requests

- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/components/VisualizationTypeSelector/styles/VisualizationTypeSelector.style.js
To make it compliant to Joe's design.
The green color for the selected state is fixed in the `task/use-d2-ui-theme branch`.
> DHIS2-5265, DHIS2-5267: style fixes for chart type selector

- packages/app/src/components/Dimensions/Dialogs/DataDimension/DataDimension.js
Fixes DHIS2-5435.
Steps to reproduce the bug:
1. File -> new
2. Open data dimension dialog, select an indicator, then click Hide
3. File -> new
4. Open data dimension dialog.
The indicator selected in step 2 is not in the available list.
> Fix consistency of data dimension unselected list options over time

- packages/app/package.json
- packages/app/src/index.js
- yarn.lock
fix/add url-polyfill for URLSearchParams
> add url-polyfill for URLSearchParams (backport to 2.31)

- packages/app/i18n/en.pot
- packages/app/src/components/App.js
- packages/app/src/components/ErrorBoundaries/FatalErrorBoundary.js
- packages/app/src/components/ErrorBoundaries/__tests__/FatalErrorBoundary.spec.js
- packages/app/src/components/ErrorBoundaries/__tests__/__snapshots__/FatalErrorBoundary.spec.js.snap
- packages/app/src/components/ErrorBoundaries/styles/FatalErrorBoundary.style.js
From https://github.com/dhis2/data-visualizer-app/pull/153
> 2.31 - Error Boundary backport

- packages/app/src/components/Dimensions/Dialogs/DataDimension/Groups.js
This PR includes:
check if user have selected a group value in "Event Data Items" and "Program Indicators" before rendering the placeholder.
Currently, user are able to change Program, but the placeholder will be rendered regardless
> fix/validate selected groups before rendering placeholder in "Event Data Items" and "Program Indicators" [DHIS2-5452]

- packages/app/src/actions/__tests__/index.spec.js
- packages/app/src/actions/index.js
- packages/app/src/actions/ui.js
- packages/app/src/reducers/ui.js
Keep the same pattern for action names
> Rename action for right sidebar opening

- packages/app/i18n/en.pot
- packages/app/src/modules/dataTypes.js
> task/v31/use 'Select a program' instead of 'Select Program' in data dimension selector

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Layout/PieLayout/PieLayout.js
- packages/app/src/components/Visualization/BlankCanvas.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/components/Visualization/__tests__/BlankCanvas.spec.js
- packages/app/src/components/Visualization/styles/BlankCanvas.style.js
- packages/app/src/modules/colors.js
- packages/app/src/modules/current.js
- packages/app/src/modules/layout.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/layoutValidation.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/current.js
- yarn.lock
See explanation here: https://jira.dhis2.org/browse/DHIS2-5605
- Adds /components/Layout/PieLayout
- Extracts and adds modules: layoutAdapters.js and layoutValidation.js
NB: Requires d2-charts-api@31.0.11
> Add specific layout for pie charts

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/Layout/Layout.js
- packages/app/src/components/Visualization/BlankCanvas.js
- packages/app/src/modules/layoutValidation.js
- packages/app/src/modules/ui.js
- packages/app/src/reducers/current.js
- yarn.lock
Adds new gauge layout. Reuses pie layout, adapters and validation where possible.
> Add gauge layout

- packages/app/src/modules/__tests__/layoutAdapters.spec.js
Add tests for pieLayoutAdapter and yearOverYearLayoutAdapter.
> Add layout adapter tests

- packages/app/src/components/Dimensions/Dialogs/Item.js
- packages/app/src/components/Dimensions/Dialogs/__tests__/Item.spec.js
Fixes [DHIS2-5893]
* Check event.ctrlKey as well as event.metaKey
* Add a few unit tests
> fix/enable multi-select of dimensions on Windows v31 [DHIS2-5893]

- packages/app/package.json
- yarn.lock
Update interpretations after changing the link placeholder from link-title to link-url and updated the version
> update d2-ui-interpretations version

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
This PR updates d2-charts-api version.
> chore: Update d2-charts-api library version

- packages/app/public/index.html
> fix: manifest bug in chrome

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/AxisSetup/AxisSetup.js
- packages/plugin/package.json
- yarn.lock
- Update label
- Update d2ca dependency
> Fix second axis label bug (#252)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: only point series to axes for certain types

- packages/app/package.json
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/plugin/package.json
- yarn.lock
* Add dx check
* Remove Menu config
* Add d2-charts-api@32.0.4
* Minor
> Fix/dual axis item check (#266)

- packages/app/src/components/Layout/Menu.js
> fix: Close context menu on item click in Chip component (backport to v32)

- packages/app/package.json
- yarn.lock
> Add d2-ui-core v5.3.8

- packages/plugin/src/ChartPlugin.js
> fix: deep check styles for changes

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> backport(v32): bumped version of d2-charts-api

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> chore(): bumped version of d2-charts-api

- packages/app/src/components/Visualization/Visualization.js
> fix: Typo in using i18n [v31]

- packages/app/src/components/Visualization/Visualization.js
> fix: Typo in using i18n [v32]

- packages/app/package.json
- yarn.lock
> chore: update dep for biweekly support

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: update charts api dep

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/AxisSetup/AxisSetup.js
- packages/app/src/components/Interpretations/Interpretations.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/index.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/plugin/package.json
- yarn.lock
- Updating `data-visualizer-plugin` version to 33.0.3
- Some prettier fixes
> chore: Update DV plugin version

- packages/app/package.json
- yarn.lock
Update interpretations package.
Update includes removal of "apply" button on new interpretations.
Ticket [DHIS2-6250](https://jira.dhis2.org/browse/DHIS2-6250)
> chore: update interpretations panel [DHIS2-6250]

- packages/app/src/components/Layout/Chip.js
> fix: remove colon from chip if no selection

- packages/app/src/components/App.css
- packages/app/src/components/App.js
Fix the layout/toolbar vertical resize issue by removing the 0% flex basis that was part of our flex-1 rule.
> fix: replace flex-1 rule with flex-grow-1

- packages/app/src/components/App.css
- packages/app/src/components/App.js
Backporting https://github.com/dhis2/data-visualizer-app/pull/323
> fix: backport #323

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> feat: multiple orgunit roots support

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
(cherry picked from commit 72eb5db4d9f0ab2953ef7ee3ff71511622f454f4)
> backport: pie tooltip DHIS2-7532

- packages/app/config/webpack.config.dev.js
- packages/app/config/webpack.config.prod.js
- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/DimensionsPanel/__tests__/DimensionsPanel.spec.js
- yarn.lock
Fixes DHIS2-7446 and DHIS2-7679.
> feat: multiple org units support v32

- packages/app/package.json
- packages/app/src/api/organisationUnits.js
- packages/app/src/components/Dimensions/Dialogs/OrgUnitDimension/OrgUnitDimension.js
- yarn.lock
Fixes DHIS2-7446 and DHIS2-7679.
> feat: multiple org units support v31

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/Tooltip.js
- packages/app/src/components/Layout/YearOverYearLayout/YearOverYearAxis.js
- packages/app/src/components/Layout/styles/Chip.style.js
- packages/app/src/modules/layoutValidation.js
- packages/plugin/package.json
- yarn.lock
DO NOT MERGE, depends on https://github.com/dhis2/analytics/pull/152/files
> fix: use locked dimensions rule from analytics

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: @dhis2/analytics 2.6.11

- packages/app/src/components/Layout/Chip.js
Fix the message params so that it shows the correct message.
> fix: tooltip message

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/plugin/package.json
- yarn.lock
This is to keep master stable while we are using the epic branch as our main dev branch for a period.
> fix: pin to analytics@2.6.11

- packages/app/package.json
- packages/app/src/modules/layout.js
- packages/app/src/reducers/__tests__/ui.spec.js
- packages/app/src/reducers/ui.js
- packages/plugin/package.json
- yarn.lock
Implement rule called "maxNumberOfDimsPerAxis".
Rely on this when transferring dimensions to/within the layout.
> fix: impl max dims rule

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fix by upgrading to @dhis2/analytics@2.4.6
> fix: epi curve (v33)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fix epi curve bug by upgrading @dhis2/analytics to 2.4.6 and d2-charts-api to 32.0.8.
Also publishing a new 32 based plugin for the dashboard.
> fix: epi curve bug (v32)

- packages/app/package.json
- packages/app/src/AppWrapper.js
- packages/app/src/actions/index.js
- packages/app/src/components/App.js
- packages/app/src/components/TitleBar/TitleBar.js
- packages/app/src/components/VisualizationOptions/Options/MeasureCriteria.js
- packages/app/src/components/VisualizationOptions/Options/ParamOrganisationUnit.js
- packages/app/src/components/VisualizationOptions/Options/ParamParentOrganisationUnit.js
- packages/app/src/components/VisualizationOptions/Options/ParamReportingPeriod.js
- packages/app/src/modules/fields/baseFields.js
- packages/app/src/modules/options.js
- packages/plugin/src/modules/options.js
- yarn.lock
Marking it as WIP as I didn't test saving various AOs.
Also, the backend changes are not in master yet, so it needs a dedicated backend running a branch from Maikel.
Requires a modified backend.
You can run the following command for spinning up a d2 cluster for testing:
`d2 cluster up visapitest --verbose -i marabori/dhis2-7946:dhis-7946-tomcat-9.0.27-jdk11-openjdk-slim --db-version dev --channel dev --seed`
> refactor: use visualization API endpoint

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
We've revamped how dependency resolution works in dhis2/app-platform#221 (v3.1.0)
> fix: upgrade cli-app-scripts to fix dependency resolution

- packages/app/src/actions/index.js
- packages/app/src/api/dataStatistics.js
Add chart view data statistics on vis load.
> fix: add dataStatistics on vis load

- packages/app/package.json
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/DimensionsPanel/__tests__/DimensionsPanel.spec.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Layout/Menu.js
- packages/app/src/components/VisualizationTypeSelector/VisualizationTypeSelector.js
- packages/app/src/reducers/ui.js
- yarn.lock
This solves some problems like the reordering of dimensions in layout
and simplifies the whole codebase as we can always just get the current
layout from the store.
> refactor: remove adapted layout

- packages/app/src/components/Layout/Layout.js
Retrofitted https://github.com/dhis2/data-visualizer-app/pull/487 to be merged to `Epic`
> fix: use layout type to get the right layout comp

- packages/app/src/components/Layout/Chip.js
Get updated values for class vars by turning them into functions.
> fix: inconsistent chip behaviour

- packages/app/package.json
- yarn.lock
For fixing issues in DHIS2-8118.
> chore: update d2-ui-interpretations version

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/DimensionsPanel/Dialogs/DialogManager.js
- packages/app/src/components/DimensionsPanel/Dialogs/__tests__/DialogManager.spec.js
- packages/app/src/components/DimensionsPanel/DimensionsPanel.js
- packages/app/src/components/Layout/Chip.js
- packages/app/src/components/Layout/DefaultLayout/DefaultAxis.js
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/modules/current.js
- packages/app/src/modules/error.js
- packages/app/src/modules/layoutAdapters.js
- packages/app/src/modules/layoutValidation.js
- packages/app/src/reducers/__tests__/dimensions.spec.js
- packages/app/src/reducers/dimensions.js
- packages/plugin/package.json
- yarn.lock
* Adds Assigned Categories to the Dimensions Panel
* Updated handling of AC in the layout
* Refactored handling of dimensions to reflect the new Analytics changes (`fixed`, `dynamic`, `predefined` etc)
* Depends on https://github.com/dhis2/analytics/pull/262
> fix: assigned categories and new dimension types

- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/AxisRange.js
- packages/app/src/components/VisualizationOptions/Options/BaseLineLabel.js
- packages/app/src/components/VisualizationOptions/Options/BaseLineValue.js
- packages/app/src/components/VisualizationOptions/Options/MeasureCriteria.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisMaxValue.js
- packages/app/src/components/VisualizationOptions/Options/RangeAxisMinValue.js
- packages/app/src/components/VisualizationOptions/Options/RegressionType.js
- packages/app/src/components/VisualizationOptions/Options/SelectBaseOption.js
- packages/app/src/components/VisualizationOptions/Options/TargetLineLabel.js
- packages/app/src/components/VisualizationOptions/Options/TargetLineValue.js
- packages/app/src/components/VisualizationOptions/Options/TextBaseOption.js
- packages/app/src/modules/options/columnConfig.js
- yarn.lock
> fix: fix styling issues in options

- packages/app/package.json
- packages/app/src/components/DimensionsPanel/DndDimensionsPanel.js
- packages/app/src/components/DimensionsPanel/styles/DndDimensionList.module.css
- packages/app/src/components/DimensionsPanel/styles/DndDimensionsPanel.module.css
- packages/plugin/package.json
- yarn.lock
* Dimensions panel's scrollbar and padding
* Upgraded to Analytics v3.1.1 for various UI fixes
> fix: ui glitches

- packages/app/i18n/en.pot
- packages/app/src/api/analytics.js
- packages/app/src/components/DownloadMenu/DownloadMenu.js
Also added missing optional parameters controlled by
options/interpretations.
There are some more parameters that could be passed, looking at this list: https://docs.dhis2.org/master/en/developer/html/webapi_analytics.html#webapi_analytics_query_parameters.
The current implementation in `d2-analysis` seems not all correct.
@janhenrikoverland do we really need support for all those? also the ones that were never handled in the classic apps?
> fix: download menu options for PT (DHIS2-8207)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
https://github.com/dhis2/analytics/pull/285
> fix: update analytics to 3.1.2 (#285)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds analytics@2.4.8
Implements this fix: dhis2/analytics#285
> fix: only run empty check after all values have been added

- packages/app/src/modules/__tests__/layoutAdapters.spec.js
- packages/app/src/modules/layoutAdapters.js
Make sure empty arrays are not shifted.
> fix: update recuder to handle empty axes

- package.json
- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/BaseLine.js
- packages/app/src/components/VisualizationOptions/Options/BaseLineLabel.js
- packages/app/src/components/VisualizationOptions/Options/TargetLine.js
- packages/app/src/components/VisualizationOptions/Options/TargetLineLabel.js
- packages/app/src/modules/current.js
- packages/app/src/modules/options/config.js
- packages/app/src/modules/options/gaugeConfig.js
- packages/plugin/package.json
- yarn.lock
Adds support for plot lines and custom range values options for Gauge charts
Depends on https://github.com/dhis2/analytics/pull/288
> fix: gauge plot lines and range values in options

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/app/src/components/DownloadMenu/DownloadMenu.js
- packages/plugin/package.json
- yarn.lock
* Updated a header in the download menu
* Latest Analytics for the lock icon alignment (https://github.com/dhis2/analytics/releases/tag/v3.3.2)
* Regenerated the pot file, as was previously forgotten in other PRs.
> fix: minor ui glitches

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
See https://github.com/dhis2/analytics/pull/304
> fix: correct number parsing and rendering with @dhis2/analytics@3.3.3

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
This also fixes a string value-parsing issue for total cells
> fix: add pivot table legend support, upgrade to @dhis2/analytics@4.1.0

- packages/app/package.json
- packages/app/src/components/App.css
- packages/plugin/package.json
- yarn.lock
Fixes the height issue in Safari for DV (https://jira.dhis2.org/browse/DHIS2-8277) by updating the app-platform dep (fixes the container height) and setting an explicit height for the `main-center-canvas` (fixes the height of the main content).
Deps on https://github.com/dhis2/app-platform/pull/303
Correct height:
> fix: height in safari (DHIS2-8277)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements the bug fix from https://github.com/dhis2/analytics/pull/321 by upgrading the Analytics dep to v4.1.4
Fixed:
> fix: gauge range bug

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
This upgrades @dhis2/analytics to 4.3.0 to support:
* FIlter title rows
* by-dx legendSets
* correct aggregate types
* row- and column-percentage number types
* style options
* column sorting
* and several bug-fixes
> fix: support more pivot table features

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds analytics PR: https://github.com/dhis2/analytics/pull/329
> fix: @dhis2/analytics@4.3.1

- packages/app/i18n/en.pot
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Upgrade @dhis2/analytics to version `4.3.18` with various pivot table fixes
> fix: pivot table fixes, upgrade analytics, and fix en.pot

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds:
- https://github.com/dhis2/analytics/commit/fde12720fbffd3126f78eafb6f3f1ef252fe8093
- https://github.com/dhis2/analytics/commit/6b20bcbe1d6585a1dfa386aa0083358401a12fef
> fix: analytics@4.3.20

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds:
- https://github.com/dhis2/analytics/commit/156fedbeab1e2a59bab8946fcca3217e44998faa
- https://github.com/dhis2/analytics/commit/5ac779dfd7fef9c3e62f4c510760c0eb288a340c
> fix: analytics@4.3.21

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds:
- https://github.com/dhis2/analytics/commit/2d8e0c966f3f846b927fd9eb9a22acc6473011cc
- https://github.com/dhis2/analytics/commit/7c651fd298c82dd0193e5a40cab48da55f323b22
> fix: analytics@4.3.22 (DHIS2-8486)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Adds
- https://github.com/dhis2/analytics/commit/b7568ddead9765880570fbd2506e912aa234623d
- https://github.com/dhis2/analytics/commit/46ce05f2851289e66b90e963af16bcca65a2b6a3
> fix: @dhis2/analytics@4.3.25 (DHIS2-8497)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Update analytics dependency to 4.3.25
> fix: analytics@4.3.25

- packages/app/src/components/scrollbar.css
Description and screenshot here: https://jira.dhis2.org/browse/DHIS2-8672
> fix: consistent scrollbar style (DHIS2-8672)

- .dependabot/config.yml
Auto merge upgrade PRs that match `semver:minor`.
> chore: auto merge semver:minor

- packages/app/package.json
- packages/app/src/components/Visualization/Visualization.js
- packages/plugin/i18n/en.pot
- packages/plugin/package.json
- packages/plugin/src/ContextualMenu.js
- packages/plugin/src/PivotPlugin.js
- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/api/organisationUnits.js
- packages/plugin/src/assets/ArrowDownwardIcon.js
- packages/plugin/src/assets/ArrowUpwardIcon.js
- packages/plugin/src/styles/VisualizationPlugin.style.js
- yarn.lock
Requires: https://github.com/dhis2/analytics/pull/445
Fixes https://jira.dhis2.org/browse/DHIS2-8769
Backported from master.
(cherry picked from commit 747e6f74f6dd0a973ff2d1bef03ff6b26cd10cba)
Refer to PR #999 for more information.
> feat: drill down/up for pivot tables [v34]

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fix for https://jira.dhis2.org/browse/DHIS2-8638
> fix: upgrade dhis2 dependencies for translations [v33] [DHIS2-8638]

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fix for https://jira.dhis2.org/browse/DHIS2-8892
> fix: upgrade d2-ui dependencies for latest translations [v32] [DHIS2-8892]

- packages/app/src/components/Layout/YearOverYearLayout/YearOverYearSelect.js
- packages/app/src/modules/__tests__/yearOverYear.spec.js
- packages/app/src/modules/yearOverYear.js
Some missed translations
[DHIS2-8894](https://jira.dhis2.org/browse/DHIS2-8894)
> fix: year-over-year translations [34.x] [DHIS2-8894]

- .github/workflows/dhis2-artifacts.yml
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- config/polyfills.js
- package.json
- packages/app/config/env.js
- packages/app/config/paths.js
- packages/app/config/webpack.config.dev.js
- packages/app/config/webpack.config.prod.js
- packages/app/config/webpackDevServer.config.js
- packages/app/cypress/plugins/index.js
- packages/app/scripts/build.js
- packages/plugin/src/ChartPlugin.js
- yarn.lock
Description: https://github.com/dhis2/data-visualizer-app/pull/1081
> chore: add deploy-build (33.x)

- .github/workflows/dhis2-artifacts.yml
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- config/polyfills.js
- package.json
- packages/app/config/env.js
- packages/app/config/paths.js
- packages/app/config/webpack.config.dev.js
- packages/app/config/webpack.config.prod.js
- packages/app/config/webpackDevServer.config.js
- packages/app/cypress/plugins/index.js
- packages/app/package.json
- packages/app/scripts/build.js
- yarn.lock
> chore: add deploy-build (32.x)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/553**
Fixes [TECH-397](https://jira.dhis2.org/browse/TECH-397)
* Bumps @dhis2/cli-app-scripts to latest
* Bumps @dhis2/ui
* Bumps @dhis2/analytics
> feat: bump cli-app-scripts, ui and analytics (TECH-397)

- packages/app/src/components/VisualizationOptions/Options/TextBaseOption.js
Backports https://github.com/dhis2/data-visualizer-app/pull/1212 to v32
* fix: pass number value as number
> fix: pass y-axis steps as number (DHIS2-9194) v32

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: build error from Analytics (DHIS2-9413)

- packages/app/i18n/en.pot
- packages/app/src/actions/index.js
Backports https://github.com/dhis2/data-visualizer-app/pull/1232 to v34
Clean cherry-pick of https://github.com/dhis2/data-visualizer-app/commit/f9fc26b9b25dbf9f43a71d13cc67c257db213b1c
-----
Proof
> fix: set a default name if saved vis is untitled (DHIS2-9360) v34

- packages/app/package.json
- packages/app/src/components/App.css
- packages/plugin/package.json
- yarn.lock
**Depends on https://github.com/dhis2/analytics/pull/602**
- Bumps the Analytics dep to get the latest d2-ui-org-unit-dialog
- Removes the old temporary css fix
> fix: org unit dialog zindex

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Add "@dhis2/analytics": "^11.0.7"
> fix: upgrade analytics

- packages/app/package.json
- yarn.lock
Backport for fixing [DHIS2-9382](https://jira.dhis2.org/browse/DHIS2-9382) in 32.x.
> fix: rich text parsing issue (DHIS2-9382) v32

- yarn.lock
Fixes [DHIS2-9547](https://jira.dhis2.org/browse/DHIS2-9547)
See jira ticket. Fixed by deduping @dhis2/ui dependencies in yarn.lock.
Before:
After:
> fix: dropdowns hidden behind dialogs (DHIS2-9547)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
bump Analytics, which should've been done in https://github.com/dhis2/data-visualizer-app/pull/1532
> fix: bump Analytics dep

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> chore: bump ui to latest

- package.json
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
- Bumps Analytics to latest version
- Adds a resolution for `@dhis2/ui`
> fix: ui resolution and analytics bump

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Updates analytics deps to 4.5.29.
> fix: update analytics deps

- yarn.lock
Resolve `@dhis2/ui` to only use 6.1.3
> chore: resolve ui

- packages/app/src/components/VisualizationOptions/NoticeBox.js
- packages/app/src/modules/options/pivotTableConfig.js
Implements [DHIS2-10269](https://jira.dhis2.org/browse/DHIS2-10269)
---
1. Warn the user about PT options that only apply to legacy standard reports
---
> fix: add a warning in PT Parameters tab (DHIS2-10269)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Because Dependabot had a day off
> chore: bump Analytics to latest

- package.json
- packages/app/package.json
- packages/app/src/components/VisualizationOptions/Options/ExtremeLines.js
- packages/app/src/components/VisualizationOptions/Options/OutlierDetectionMethod.js
- packages/plugin/package.json
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/837**
---
1. Use min/step props on ui Input fields for outliers options
---
Outliers options need validation on input fields for **threshold factor** and **Extreme line % detection**.
The newly introduced min/max/step props on `@dhis2/ui` Input fields are used for this, setting a lower limit value and the step increment.
> fix: min/step settings for outliers options

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: @dhis2/analytics@16.0.3

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: @dhis2/analytics@16.0.8

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: @dhis2/analytics@16.0.9

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix: @dhis2/analytics@16.0.11

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
> fix(deps): upgrade analytics

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backports [DHIS2-9829](https://jira.dhis2.org/browse/DHIS2-9829) to v35
**Requires https://github.com/dhis2/analytics/pull/874**
> fix: render trendlines in front of columns (DHIS2-9829) v35

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backports [DHIS2-9829](https://jira.dhis2.org/browse/DHIS2-9829) to v33
**Requires https://github.com/dhis2/analytics/pull/873**
> fix: render trendlines in front of columns (DHIS2-9829) v33

- yarn.lock
Implements [DHIS2-10988](https://jira.dhis2.org/browse/DHIS2-10988)
**Requires https://github.com/dhis2/analytics/pull/903**
---
1. Bump Analytics to latest version
> fix: paging of dynamic dimension items (DHIS2-10988)

- packages/app/src/api/mostViewedVisualizations.js
- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/components/Visualization/__tests__/utils.spec.js
- packages/app/src/components/Visualization/utils.js
Backport / cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/1709 and https://github.com/dhis2/data-visualizer-app/pull/1711 to v36
> fix: start screen most viewed updates v36 (DHIS2-11065)

- packages/app/src/api/mostViewedVisualizations.js
- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/components/Visualization/__tests__/utils.spec.js
- packages/app/src/components/Visualization/utils.js
Backport / cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/1712 to v35
> fix: start screen most viewed updates v35 (DHIS2-11065)

- packages/app/src/api/mostViewedVisualizations.js
- packages/app/src/components/Visualization/StartScreen.js
- packages/app/src/components/Visualization/__tests__/utils.spec.js
- packages/app/src/components/Visualization/utils.js
Backport / cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/1712 to v34
> fix: start screen most viewed updates v34 (DHIS2-11065)

- cypress/integration/dimensions/period.cy.js
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-7029](https://jira.dhis2.org/browse/DHIS2-7029)
**Requires https://github.com/dhis2/analytics/pull/924**
---
1. Add the period ´Last 10 years´ by bumping Analytics to latest
2. Change the Cypress test for the `Years` period type to factor in the new type
---
> feat(deps): add last 10 years relative period (DHIS2-7029)

- cypress/elements/optionsModal/axes.js
- cypress/elements/optionsModal/index.js
- cypress/elements/optionsModal/series.js
- cypress/integration/open.cy.js
- cypress/integration/options/axes.cy.js
- cypress/integration/options/fontStyles.cy.js
- cypress/utils/window.js
- packages/app/src/components/VisualizationOptions/Options/AxisDecimals.js
- packages/app/src/components/VisualizationOptions/Options/AxisSteps.js
- packages/app/src/components/VisualizationOptions/Options/AxisTitle.js
- packages/app/src/components/VisualizationOptions/Options/PositiveNumberBaseType.js
- packages/app/src/components/VisualizationOptions/Options/SeriesTable.js
Implements tests for [DHIS2-6672](https://jira.dhis2.org/browse/DHIS2-6672)
Tests the following options:
- Steps
- Decimals (can only be enabled but not evaluated)
- Auto generated axis titles for single and multi axis
> test: new tests for multi axis options (DHIS2-6672)

- packages/app/package.json
- yarn.lock
1. bumps `d2-ui-interpretations` version
---
Avoids a crash when opening the interpretations panel with a locale with `language_country` format
See https://github.com/dhis2/d2-ui/pull/700
> fix: fix locale format passed to Intl in interpretations v36

- packages/app/package.json
- yarn.lock
1. bumps `d2-ui-interpretations` version
---
Avoids a crash when opening the interpretations panel with a locale with `language_country` format
See https://github.com/dhis2/d2-ui/pull/700
> fix: fix locale format passed to Intl in interpretations v34

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-11304](https://jira.dhis2.org/browse/DHIS2-11304)
---
The upgrade to analytics includes providing default font size for visualizations
> chore: upgrade @dhis2/analytics

- README.md
This is to trigger a publish of the plugin
> fix: update description in README

- packages/app/package.json
- packages/app/src/components/App.js
- yarn.lock
Code changes needed before this upgrade is possible
> chore: revert bump react-redux from 5.1.2 to 7.2.4

- packages/app/i18n/en.pot
- packages/app/src/components/VisualizationOptions/Options/AxisTitle.js
- packages/app/src/components/VisualizationOptions/Options/TextStyle.js
- packages/app/src/components/VisualizationOptions/styles/TextStyle.module.css
Implements bug fixes for [DHIS2-6672](https://jira.dhis2.org/browse/DHIS2-6672), found in a KFMT session
---
1. Axis title `Auto generated` -> `Auto generated from axis items`
2. Wrap `TextStyle` buttons to avoid horisontal scrollbar
---
_previously_
_now_
> fix: minor axis options changes (DHIS2-6672)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-7420](https://jira.dhis2.org/browse/DHIS2-7420)
**Requires https://github.com/dhis2/analytics/pull/952**
---
The implementation is in analytics, see the analytics PR linked above.
> feat: show indicator type in SV

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Update @dhis2/analytics,  @dhis2/ui, @dhis2/app-runtime to latest
> fix: bump @dhis2/analytics, @dhis2/ui, @dhis2/app-runtime to latest

- packages/app/package.json
- packages/app/src/modules/fields/baseFields.js
- packages/plugin/package.json
- packages/plugin/src/modules/options.js
- yarn.lock
**Backports to the following PRs**
* https://github.com/dhis2/data-visualizer-app/pull/1870
* https://github.com/dhis2/data-visualizer-app/pull/1857
* https://github.com/dhis2/data-visualizer-app/pull/1868
* https://github.com/dhis2/data-visualizer-app/pull/1871
84a52e45 - fix: rename options for PT fixed headers
90f0376b - fix: retrieve options for PT fixed headers
> fix: several backports to [37.x]

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- yarn.lock
Implements [DHIS2-XXXX](https://jira.dhis2.org/browse/DHIS2-XXXX)
---
1. Prevents the app from crashing when `visualization.series` is undefined
2. Downgrades `@dhis2/app-runtime` to only have 1 version of the lib in use
---
_before_
_after_
> fix: undefined series + downgrade app-runtime

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- yarn.lock
Cherry-pick backport of https://github.com/dhis2/data-visualizer-app/pull/1876
> fix: undefined series + downgrade app-runtime (#1876) 37.x

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Part of the implementatio of [DHIS2-11810](https://jira.dhis2.org/browse/DHIS2-11810)
---
1. use a different color for the No data text
> fix: fix color for No data text in SV DHIS2-11810

- CHANGELOG.md
- package.json
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport for [DHIS2-11810](https://jira.dhis2.org/browse/DHIS2-11810)
> fix: update analytics with SV no data fix 2.37.0

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-11835](https://jira.dhis2.org/browse/DHIS2-11835)
**Requires https://github.com/dhis2/analytics/pull/1053**
---
1. Fix fixed row headers bug
---
The actual fix in the analytics library. See its PR linked above.
> fix: update analytics with fix for PT fixed row headers

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
(cherry picked from commit bcb99a3f9a4dbdf802430c260fb10916a5b1bdf9)
Fixes [DHIS2-11835](https://jira.dhis2.org/browse/DHIS2-11835)
**Requires https://github.com/dhis2/analytics/pull/1053**
---
1. Fix fixed row headers bug
---
The actual fix in the analytics library. See its PR linked above.
> fix: update analytics with fix for PT fixed row headers v37

- packages/app/src/components/Layout/ScatterLayout/styles/ScatterAxis.style.js
Implements [DHIS2-11849](https://jira.dhis2.org/browse/DHIS2-11849)
---
See jira ticket.
---
Before:
After:
> fix: scatter layout dx chip behaviour

- packages/app/src/components/Layout/ScatterLayout/styles/ScatterAxis.style.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1901
> fix: scatter dx chip position [v37]

- packages/app/src/components/Layout/ScatterLayout/styles/ScatterAxis.style.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/1901
> fix: scatter dx chip position

- CHANGELOG.md
- package.json
- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Backport of [DHIS2-11835](https://jira.dhis2.org/browse/DHIS2-11835)
> fix: update analytics with fix for PT fixed row headers 2.37.0

- packages/app/src/components/Visualization/Visualization.js
Fixes [DHIS2-12130](https://jira.dhis2.org/browse/DHIS2-12130)
---
1. Backports https://github.com/dhis2/data-visualizer-app/pull/1624 to 34.x
---
> fix: store metadata when no data is returned (DHIS2-12130) v34

- packages/app/src/components/Visualization/Visualization.js
Fixes [DHIS2-12130](https://jira.dhis2.org/browse/DHIS2-12130)
---
1. Backports https://github.com/dhis2/data-visualizer-app/pull/1624 to 35.x
---
> fix: store metadata when no data is returned (DHIS2-12130) v35

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-8174](https://jira.dhis2.org/browse/DHIS2-8174)
**Requires https://github.com/dhis2/analytics/pull/1121**
---
1. Backport for v33
---
See https://github.com/dhis2/analytics/pull/1121
> fix: backport for DHIS2-8174 v33

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes [DHIS2-8174](https://jira.dhis2.org/browse/DHIS2-8174)
**Requires https://github.com/dhis2/analytics/pull/1122**
---
1. Backport for v34
---
See https://github.com/dhis2/analytics/pull/1122
> fix: backport for DHIS2-8174 v34

- packages/app/package.json
- packages/app/src/components/TitleBar/TitleBar.js
- packages/plugin/package.json
- yarn.lock
Backport fix for [DHIS2-13015](https://jira.dhis2.org/browse/DHIS2-13015)
Requires https://github.com/dhis2/analytics/pull/1198
---
1. backport of #2017
> fix: backport fix for DHIS2-13015 (37.x)

- packages/app/src/components/UserSettingsProvider.js
Clean backport of https://github.com/dhis2/data-visualizer-app/pull/2043
> fix: correct typo with display name property (DHIS2-10174) v38

- packages/app/src/components/UserSettingsProvider.js
Clean backport of https://github.com/dhis2/data-visualizer-app/pull/2043
> fix: correct typo with display name property (DHIS2-10174) v37

- packages/app/package.json
- yarn.lock
Implements [DHIS2-12617](https://jira.dhis2.org/browse/DHIS2-12617)
---
1. bump d2-ui-interpretation dependency to fix access issue
See ticket and [this PR](https://github.com/dhis2/d2-ui/pull/724).
> fix: bump d2-ui-interpretation dependency for DHIS2-12617

- packages/app/package.json
- packages/app/src/components/MenuButton/styles/MenuButton.module.css
- packages/plugin/package.json
- yarn.lock
Implements [TECH-1145](https://jira.dhis2.org/browse/TECH-1145)
**Requires https://github.com/dhis2/analytics/pull/1215**
---
1. remove `min-width` from the MenuBar buttons
2. increase lateral padding for spacing more the buttons
---
The `min-width` was causing inconsistent spacing between buttons in the MenuBar in analytics apps.
---
Before:
After:
> fix: remove min-width from MenuBar buttons TECH-1145

- packages/app/package.json
- packages/plugin/package.json
- packages/plugin/src/api/analytics.js
- yarn.lock
Implements [DHIS2-12580](https://jira.dhis2.org/browse/DHIS2-12580)
**Requires https://github.com/dhis2/analytics/pull/1247**
---
1. backport of #2065 
---
-   [x] update analytics to latest 21.x version
> fix: use normal handling when WEEKS_THIS_YEAR is used in YoY DHIS2-12580 (38.x)

- packages/app/package.json
- yarn.lock
Implements [DHIS2-12617](https://jira.dhis2.org/browse/DHIS2-12617)
---
1. backport of #2046 
---
Fixes DHIS2-12617 for DV 38.x
> fix: bump d2-ui-interpretations dep for DHIS2-12617 (38.x)

- packages/app/package.json
- yarn.lock
Implements [DHIS2-12617](https://jira.dhis2.org/browse/DHIS2-12617)
---
1. backport of #2046 
---
Fixes DHIS2-12617 for DV patch/2.38.1
> fix: bump d2-ui-interpretations dep for DHIS2-12617 (patch/2.38.1) (#2113)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-13328](https://jira.dhis2.org/browse/DHIS2-13328)
**Requires https://github.com/dhis2/analytics/pull/1325**
---
Bumps Analytics to latest. See the Analytics PR for more details.
---
> fix: change default value for Save as (DHIS2-13328)

- .github/workflows/cypress.yml
- cypress/elements/startScreen.js
- cypress/integration/dimensions.cy.js
- packages/app/package.json
- yarn.lock
Implements [DHIS2-12617](https://jira.dhis2.org/browse/DHIS2-12617)
---
1. backport of #2046 
---
Fixes DHIS2-12617 for DV 36.x
> fix: bump interpretations component for DHIS2-12617 (36.x)

- packages/app/src/components/DetailsPanel/DetailsPanel.js
Backports 709449e3e53b9bbb6ca40152d94a609342e0cf73
> fix: pass correct prop for analytics breaking change

- packages/app/src/components/DetailsPanel/DetailsPanel.js
Implements [DHIS2-13740](https://jira.dhis2.org/browse/DHIS2-13740)
---
1. backport of the fix done in master and patch/2.39.0
---
This is needed to avoid losing the fix in the patches after 2.39.0
> fix: pass correct prop for analytics break. change (DHIS2-13740) (39.x)

- package.json
- src/components/App.css
- src/components/DimensionsPanel/DndDimensionsPanel.js
- src/components/DimensionsPanel/styles/DimensionsPanel.style.js
- src/components/DimensionsPanel/styles/DndDimensionList.module.css
- src/components/DimensionsPanel/styles/DndDimensionsPanel.module.css
- src/components/Visualization/styles/StartScreen.module.css
- yarn.lock
Implements [UX-130](https://dhis2.atlassian.net/browse/UX-130)
---
Updates Data Visualizer color, spacing, and typography usage to better match the updated styles defined by Line Listing app. 
---
Before:
After:
[UX-130]: https://dhis2.atlassian.net/browse/UX-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update design to match Line Listing app

- package.json
- yarn.lock
1. update `@dhis2/analytics` (SaveAs/Rename dialog spacing, GetLink URL)
2. update `@dhis2/cli-app-scripts` (index.html / plugin.html fixes)
---
Various dependency updates.
> fix: dependency updates

- package.json
- yarn.lock
1. update cli-app-scripts
2. update analytics
---
The gray background in the initial loading spinner is removed (cli-app-scripts).
More fixes to FileMenu -> GetLink (analytics).
> fix: update cli-app-scripts and analytics

- package.json
- yarn.lock
https://dhis2.atlassian.net/browse/DHIS2-15008
> fix: remove translucent layer by using app-scripts 10.3.4 (DHIS2-15008)

- package.json
- yarn.lock
1. analytics bump to address SV issues (subtasks in DHIS2-10496)
---
Various fixes for SVG issues.
More details in the analytics PR: https://github.com/dhis2/analytics/pull/1456
> chore: bump analytics

- package.json
- src/PluginWrapper.js
- src/modules/getPWAInstallationStatus.js
- yarn.lock
Fixes https://github.com/dhis2/data-visualizer-app/pull/2273
Needed by dashboard app in 2.40.0.
> fix: plugin sends installation status

- package.json
- yarn.lock
Implements [DHIS2-15344](https://jira.dhis2.org/browse/DHIS2-15344)
Fixes size and position issues related to single values. See ticket for screenshots.
[DHIS2-15344]: https://dhis2.atlassian.net/browse/DHIS2-15344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: single value svg fixes (analytics@25.1.10) (DHIS2-15344)

- package.json
- src/components/Visualization/Visualization.js
- yarn.lock
Includes
0f018f642d89edac85629c280f7afc19ef4f0fab
e864a60d69734fa48aba82a02e2f7baa5456490b
390e6b052019b357e998c8601f8b3f2536c6de92
438f3d2e28a0c60ec1b252ca287ac4d2e0a04650
> fix: v100.1.1

- .github/workflows/nightly.yml
Changes the time for the nightly run to 04:50 UTC (06:50 CEST)
> chore: advance the schedule for the nightly run

- cypress/integration/dimensions/data.cy.js
- package.json
- yarn.lock
Fixes [DHIS2-15750](https://jira.dhis2.org/browse/DHIS2-15750)
**Requires https://github.com/dhis2/analytics/pull/1572**
---
1. bump analytics
---
See description in the [analytics PR](https://github.com/dhis2/analytics/pull/1572).
[DHIS2-15750]: https://dhis2.atlassian.net/browse/DHIS2-15750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: translate dimension labels in PT DHIS2-15750

- package.json
- yarn.lock
Upgrade analytics from 26.1.2 to 26.1.6.
> fix: update analytics

- cypress/integration/options/legend.cy.js
- packages/plugin/src/VisualizationPlugin.js
Implements [DHIS2-12830](https://jira.dhis2.org/browse/DHIS2-12830)
---
See https://github.com/dhis2/data-visualizer-app/pull/2753 for more info
[DHIS2-12830]: https://dhis2.atlassian.net/browse/DHIS2-12830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: legend sets fail to load in table with data dimension in the row (DHIS2-12830) v39

- cypress/integration/options/legend.cy.js
- packages/plugin/src/VisualizationPlugin.js
Implements [DHIS2-12830](https://jira.dhis2.org/browse/DHIS2-12830)
---
See https://github.com/dhis2/data-visualizer-app/pull/2753 for more info
[DHIS2-12830]: https://dhis2.atlassian.net/browse/DHIS2-12830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: legend sets fail to load in table with data dimension in the row (DHIS2-12830) v38

- .github/workflows/dhis2-verify-app.yml
Add slack bot release success message. The format is identical to that used in Maps app
> chore: add slack bot release success message

- cypress/elements/dimensionsPanel.js
- cypress/integration/dimensions/data.cy.js
- cypress/integration/dimensions/dynamic.cy.js
- cypress/utils/data.js
Adapts the Cypress test suite to the new version of the database
> test: adapt tests to new database

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Fixes: https://dhis2.atlassian.net/browse/DHIS2-16392
Related analytics PR:
https://github.com/dhis2/analytics/pull/1643
PR showing the fix: https://github.com/dhis2/analytics/pull/1600
> fix: upgrade analytics for interpretations like/unlike flashing [v39]

- cypress/integration/customErrors/visualizationError.cy.js
- packages/app/i18n/en.pot
- packages/app/src/components/Visualization/Visualization.js
- packages/app/src/modules/error.js
Implements [DHIS2-10067](https://jira.dhis2.org/browse/DHIS2-10067) for v38
Cherry-pick of https://github.com/dhis2/data-visualizer-app/pull/2224
[DHIS2-10067]: https://dhis2.atlassian.net/browse/DHIS2-10067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: error message for non-numeric data types (DHIS2-10067) v38

- .d2styleignore
- packages/app/package.json
- packages/app/src/components/InterpretationModal/InterpretationModal.js
- packages/plugin/package.json
- packages/plugin/src/VisualizationPlugin.js
- packages/plugin/src/styles/VisualizationPlugin.module.css
- yarn.lock
Backport of https://github.com/dhis2/data-visualizer-app/pull/3017
Fixes [DHIS2-15570](https://dhis2.atlassian.net/browse/DHIS2-15570)
**Requireshttps://github.com/dhis2/analytics/pull/1653**
[DHIS2-15570]: https://dhis2.atlassian.net/browse/DHIS2-15570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: plugin flashes when interacting with Interpretations modal [DHIS2-15570] [39.x]

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-15344](https://jira.dhis2.org/browse/DHIS2-15344)
Implements [DHIS2-13077](https://jira.dhis2.org/browse/DHIS2-13077)
Backport of the single value rendering fixes.
[DHIS2-15344]: https://dhis2.atlassian.net/browse/DHIS2-15344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-13077]: https://dhis2.atlassian.net/browse/DHIS2-13077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: analytics@24.10.8 (DHIS2-15344) (DHIS2-13077) [39.x]

- src/actions/index.js
Implements [DHIS2-13167](https://jira.dhis2.org/browse/DHIS2-13167)
---
1. Clear ao id when 404 is returned
---
-   [ ] Manual testing
---
_before and after_
https://github.com/dhis2/data-visualizer-app/assets/12590483/585f948c-7f1c-4230-9dd1-85d3bf10837a
[DHIS2-13167]: https://dhis2.atlassian.net/browse/DHIS2-13167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: non-existing AO blocks new AOs from being created (DHIS2-13167)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-16900](https://jira.dhis2.org/browse/DHIS2-16900)
**Requires https://github.com/dhis2/analytics/pull/1671**
---
Backport / bumps Analytics in a similar way as https://github.com/dhis2/data-visualizer-app/pull/3072/
[DHIS2-16900]: https://dhis2.atlassian.net/browse/DHIS2-16900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: numbers are misaligned in pivot table (DHIS2-16900) v39

- package.json
- yarn.lock
1. use improved rich text editor from analytics (DHIS2-15522)
1. separator for hundreds, thousands and millions is missing in the Pie charts (DHIS2-16172)
> fix: merge to master

- package.json
- yarn.lock
Implements [DHIS2-17611](https://jira.dhis2.org/browse/DHIS2-17611)
For details see https://github.com/dhis2/analytics/pull/1683
Upgrades to analytics@26.7.6
[DHIS2-17611]: https://dhis2.atlassian.net/browse/DHIS2-17611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: apply legend to all numeric and boolean types (DHIS2-17611)

- packages/app/package.json
- packages/plugin/package.json
- yarn.lock
Implements [DHIS2-17611](https://jira.dhis2.org/browse/DHIS2-17611)
Backports https://github.com/dhis2/data-visualizer-app/pull/3128
[DHIS2-17611]: https://dhis2.atlassian.net/browse/DHIS2-17611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: analytics@24.10.13 apply legend to all numeric and boolean types (DHIS2-17611) [39.x]

- packages/app/src/components/VisualizationOptions/Options/Subtitle.js
- packages/app/src/modules/options/pivotTableConfig.js
Backport of https://github.com/dhis2/data-visualizer-app/pull/3178
> feat: add subtitle field to pivot table options [DHIS2-16158] (V39)

- .github/workflows/verify-pr.yml
- cypress/integration/customErrors/visualizationError.cy.js
Use hardcoded dev version instead of relying on the analytics-dev instance to get this value
> chore: use hardcoded dev version for running e2e prod tests

- .github/workflows/dhis2-preview-pr.yml
- .github/workflows/dhis2-verify-commits.yml
- .github/workflows/nightly.yml
- .github/workflows/publish-d2-ci.yml
- .github/workflows/release.yml
- .github/workflows/verify-pr.yml
Implements [DHIS2-18298](https://dhis2.atlassian.net/browse/DHIS2-18298)
---
1. Upgrades all GitHub Actions
2. For actions that could not be upgraded a note explains why
[DHIS2-18298]: https://dhis2.atlassian.net/browse/DHIS2-18298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade all used github action versions [DHIS2-18298]

- .github/workflows/verify-pr.yml
- cypress.config.js
- jest.config.js
- package.json
https://dhis2.atlassian.net/browse/DHIS2-18491
> chore: remove ReportPortal integration

- cypress/integration/options/totals.cy.js
Ref https://dhis2.slack.com/archives/G0108CD1421/p1733223595061669?thread_ts=1732787482.029189&cid=G0108CD1421
Fixes the totals test by relatively selecting the same months in the current year.
> test: fix totals test by changing periods

- .gitignore
- package.json
- yarn.lock
Implements [DHIS2-17876](https://dhis2.atlassian.net/browse/DHIS2-17876)
**Requires https://github.com/dhis2/analytics/pull/1747**
---
https://github.com/user-attachments/assets/752777a5-8c08-4a03-bef9-b82784ad022c
[DHIS2-17876]: https://dhis2.atlassian.net/browse/DHIS2-17876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: pivot table crashes when hiding empty columns

- package.json
- yarn.lock
Implements [DHIS2-18976](https://jira.dhis2.org/browse/DHIS2-18976)
**Requires https://github.com/dhis2/analytics/pull/1760**
See https://github.com/dhis2/analytics/pull/1760 for info.
-   [x] KFMT
[DHIS2-18976]: https://dhis2.atlassian.net/browse/DHIS2-18976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: allow blank cumulative values in charts (DHIS2-18976)

- .github/pull_request_template.md
- .github/workflows/check-tasklist.yml
- .prettierrc.js
Avoid merging PRs without ensuring QA is complete. The workflow will require that all checkboxes are checked.
As far as the checkboxes, the main addition is for ensuring that Dashboard has been tested with the DV plugin
-   [x] is this complete?
> chore: add workflow that doesnt succeed until PR tasks completed

- package.json
- yarn.lock
Implements [DHIS2-19454](https://dhis2.atlassian.net/browse/DHIS2-19454)
See https://github.com/dhis2/analytics/pull/1772 for info.
[DHIS2-19454]: https://dhis2.atlassian.net/browse/DHIS2-19454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: print the name of relative periods instead of actual periods (DHIS2-19454)

- cypress/support/e2e.js
- package.json
- yarn.lock
Just a quick PR to upgrade the cypress utils and assert the login request
> chore: upgrade cli-utils-cypress and assert login request
